### ISSUE TITLE
w3.solidity_keccak returns different results than keccak256(abi.encode(...))

### ISSUE THREAD

**Issue by HappyDingning** [ethereum/web3.py#2966] opened 2023-05-25 16:24 UTC
Hello, I have encountered the issus of w3.solidity_keccak returns different results than keccak256(abi.encode(...)). But I'm not very familiar with web3, so I'm not really sure it's an issus. But I did find some workarounds for the problems I was having.

* Version: 6.3.0
* Python: 3.10
* OS: win
* `pip freeze` output
```
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
bitarray==2.7.3
certifi==2023.5.7
charset-normalizer==3.1.0
cytoolz==0.12.1
ecdsa==0.18.0
eth-abi==4.0.0
eth-account==0.8.0
eth-hash==0.5.1
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.3.0
eth-utils==2.1.0
frozenlist==1.3.3
hexbytes==0.3.0
idna==3.4
jsonschema==4.17.3
lru-dict==1.1.8
multidict==6.0.4
parsimonious==0.9.0
protobuf==4.23.0
pycryptodome==3.17
pyrsistent==0.19.3
pywin32==306
regex==2023.5.5
requests==2.30.0
rlp==3.0.0
six==1.16.0
toolz==0.12.0
urllib3==2.0.2
web3==6.3.0
websockets==11.0.3
yarl==1.9.2
```

### What was wrong?

``` python
from web3 import Web3

w3 = Web3(Web3.HTTPProvider('https://sepolia.infura.io/v3/xxxxxxxxxxxxxxxxxxxxxxxxx'))

print(w3.solidity_keccak(['bool'], [True]).hex())
# 0x5fe7f977e71dba2ea1a68e21057beebb9be2ac30c6410aa38d4f3fbe41dcffd2
```

``` solidity
// pragma solidity 0.8.19;

function kck256() external pure returns(bytes32) {
    bool abc = true;

    bytes32 sign = keccak256(
        abi.encode(
            abc
        )
    );

    return sign;
}

# 0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6
```

### How can it be fixed?
``` python
# web3._utils.size_of_type

def size_of_type(abi_type: TypeStr) -> int:
    """
    Returns size in bits of abi_type
    """
    if "string" in abi_type:
        return None
    if "byte" in abi_type:
        return None
    if "[" in abi_type:
        return None
    if abi_type == "bool":
        return 8   # should be 256
    if abi_type == "address":
        return 160   # 256, too
    return int(re.sub(r"\D", "", abi_type))
```

**Comment by kclowes** [comment] 2023-05-26 15:47
Thanks for raising an issue. `w3.solidity_keccak` is equivalent to Solidity's packed encoding. Check out the second code example in [the `solidity_keccak` docs](https://web3py.readthedocs.io/en/stable/web3.main.html#web3.Web3.solidity_keccak). Closing as this is not a bug.

**Closed by kclowes** 2023-05-26 15:47 UTC
