### ISSUE TITLE
Importing EthereumTesterProvider : ImportError: cannot import name 'collapse_type'

### ISSUE THREAD

**Issue by fabdarice** [ethereum/web3.py#1201] opened 2019-01-12 04:10 UTC
* Version: 4.7.2
* Python: 3.6
* OS: linux
* `pip freeze` output

```
asn1crypto==0.24.0
atomicwrites==1.2.1
attrdict==2.0.0
attrs==18.2.0
bravado-core==5.0.7
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
coincurve==9.0.0
cryptography==2.4.2
cytoolz==0.9.0.1
eth-abi==2.0.0b4
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-tester==0.1.0b36
eth-typing==1.3.0
eth-utils==1.4.1
ethereum==2.3.2
Faker==0.9.1
flake8==3.5.0
future==0.16.0
hexbytes==0.1.0
identifier-locator-client==0.1.1
idna==2.7
jsonref==0.2
jsonschema==2.6.0
lru-dict==1.1.6
mccabe==0.6.1
mock==2.0.0
more-itertools==4.3.0
msgpack-python==0.5.6
mypy==0.630
mypy-extensions==0.4.1
parsimonious==0.8.0
pbkdf2==1.3
pbr==5.1.1
pluggy==0.7.1
py==1.6.0
py-ecc==1.4.3
pycodestyle==2.3.1
pycparser==2.19
pycryptodome==3.6.6
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.8.2
python-dateutil==2.7.3
python-json-logger==0.1.9
pytz==2018.9
PyYAML==3.13
repoze.lru==0.7
requests==2.21.0
rfc3987==1.3.8
rlp==1.1.0
scrypt==0.8.6
semantic-version==2.6.0
simplejson==3.16.0
six==1.11.0
sl-secretsharing==0.2.6
-e git+git@github.com:springlabs/springcor.git@5b9890ecd4fdb77ed7e6cedb7a6bfc560f0f4f24#egg=springcor
strict-rfc3339==0.7
structlog==18.2.0
swagger-spec-validator==2.4.1
text-unidecode==1.2
toolz==0.9.0
typed-ast==1.1.0
urllib3==1.23
utilitybelt==0.2.6
web3==4.7.2
webcolors==1.8.1
websockets==6.0
```

### What was wrong?
Trying to use the EthereumTesterProvider
Receiving error from this line : `from web3 import Web3, EthereumTesterProvider`

**Comment by Ryan-Gordon** [comment] 2019-01-13 08:36
Is import `EthereumTesterProvider` something that worked previously ? 

I can see Web3 appears to hold an instance of `EthereumTesterProvider`, is this useable I wonder 🤔
Can you try importing 

```
from web3.providers.eth_tester import EthereumTesterProvider
```
For now, while we work out how this should work.
@pipermerriam should EthereumTesterProvider be a top level import?

**Comment by kclowes** [comment] 2019-01-16 18:55
@fabdarice It should work to run `from web3 import Web3, EthereumTesterProvider`. I can't reproduce an error on my machine. What is the error you're seeing?

**Comment by kclowes** [comment] 2019-01-16 19:07
Did some more digging. Looks like they removed collapse_type from eth-abi 2.0. 
From the [docs](https://eth-abi.readthedocs.io/en/latest/releases.html?highlight=collapse_type#v2-0-0-beta-1): 
> The collapse_type() function has been removed. People who still wish to use this function should replicate its logic locally and where needed.

Closing this issue, but feel free to reopen if you need more help!

**Closed by kclowes** 2019-01-16 19:07 UTC

**Comment by mrx23dot** [comment] 2022-01-06 21:37
Just a note, library versions are incompatible of these 2 packages:
pip3 install web3 mythril
on Python 3.7.3

py-evm 0.5.0a1 has requirement rlp<3,>=2, but you'll have rlp 1.2.0 which is incompatible.
