### ISSUE TITLE
Bug with `to_hex` in `wait_for_transaction_receipt` function

### ISSUE THREAD

**Issue by sobolev-igor** [ethereum/web3.py#2043] opened 2021-06-21 21:43 UTC
* Version: 5.20.0
* Python: 3.9
* OS: osx

### What was wrong?

Hey! I've got an issue with `to_hex` and `wait_for_transaction_receipt` functions. 
I use the function as in the example

> web3.eth.wait_for_transaction_receipt('0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060')

But if the tx doesn't get mined within timeout it raises the exception which uses `to_hex` function with a tx hash passed as a parameter (which is a string in an example). It raises another exception as a string cannot be passed to `to_hex` function.

> Unsupported type: The primitive argument must be one of: bytes,bytearray, int or bool and not str

### How can it be fixed?

Allow `to_hex` accept a string or convert it to bytes in `wait_for_transaction_receipt` function.

**Comment by kclowes** [comment] 2021-06-23 21:05
Thanks for raising this! Option 2 (convert it to bytes in `wait_for_transaction_receipt`) is going to be the most straightforward I think, so I'd vote for that solution.

**Comment by KingCreate** [comment] 2021-06-25 02:19
Hi, am I able to give this a crack as my first issue?

**Comment by kclowes** [comment] 2021-06-25 15:13
@KingCreate yes please! let me know if you need more direction!

**Comment by ericscagnelli** [comment] 2021-07-05 03:23
@KingCreate @kclowes Is this one still being worked or is any help needed? I'd like to give this one a try as a first issue 

Also - it looks like #2061 is a duplicate of this one

**Comment by kclowes** [comment] 2021-07-07 16:52
@ericscagnelli I haven't seen a PR yet, so as far as I can tell, it's up for grabs. Thanks!

**Comment by KingCreate** [comment] 2021-07-08 09:13
@ericscagnelli I think I need to go back and learn some more, so feel free to take this one

**Comment by abdulqgg** [comment] 2021-07-26 16:33
Could i give this a go as my first issue?

**Comment by fselmo** [comment] 2021-07-26 17:00
> Could i give this a go as my first issue?

Hey @abdulqgg. Sorry about that, looks like this was picked up and changes were merged as part of #2068 but we forgot to close it. I'm going to close this but I'd still encourage looking for a `Good First Issue` tag or anything else that seems interesting to you if you are still interested in contributing. Thanks for the interest!

**Closed by fselmo** 2021-07-26 17:00 UTC
Labels: Good First Issue
