### ISSUE TITLE
Incorrect argument count but constructor requires none

### ISSUE THREAD

**Issue by spaceh3ad** [ethereum/web3.py#2784] opened 2023-01-18 12:38 UTC
* Version: web3==5.30.0
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?

My solidity smart contract creates a instance of another smart contract which takes as a parameter the first one:

```  
  constructor() ERC721("MyNFT", "JustNFT") {
        vnft = new VerifyingNFT(address(this));
    }
   ```

I am using web3py to deploy the contract to the network. But at deployment I get:

```
Traceback (most recent call last):
  File "/home/jan-k/bc/scripts/deploy_from_be.py", line 1889, in <module>
    tx_hash = MyNFT.constructor().transact({"from": web3.eth.accounts[0]})
  File "/home/jan-k/.local/lib/python3.10/site-packages/web3/contract.py", line 391, in constructor
    return ContractConstructor(cls.web3,
  File "/home/jan-k/.local/lib/python3.10/site-packages/web3/contract.py", line 604, in __init__
    self.data_in_transaction = self._encode_data_in_transaction(*args, **kwargs)
  File "/home/jan-k/.local/lib/python3.10/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/jan-k/.local/lib/python3.10/site-packages/web3/contract.py", line 616, in _encode_data_in_transaction
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "/home/jan-k/.local/lib/python3.10/site-packages/web3/_utils/abi.py", line 440, in merge_args_and_kwargs
    raise TypeError(
TypeError: Incorrect argument count.  Expected '1'.  Got '0'
```

deployment script:
```
MyNFT = web3.eth.contract(abi=abi, bytecode=bytecode)
tx_hash = MyNFT.constructor().transact({"from": web3.eth.accounts[0]})
```

**Comment by fselmo** [comment] 2023-01-18 16:05
This does not look like an issue with the library. I'm going to close it but, if you have usage questions, a very helpful resource is the [Ethereum Python Community Discord](https://discord.gg/GHryRvPB84). Best of luck.

**Closed by fselmo** 2023-01-18 16:05 UTC

**Comment by fselmo** [comment] 2023-01-18 17:24
As a note, I just tested a simpler version of this and did not have issues.

```solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.17;

contract ERC721 {
    // Token name
    string private _name;

    // Token symbol
    string private _symbol;

    constructor(string memory name_, string memory symbol_) {
        _name = name_;
        _symbol = symbol_;
    }
}


contract VerifyingNFT {
    address public arg_addr;

    constructor(address _addr) public {
        arg_addr = _addr;
    }
}

contract MyNFT is ERC721 {
    VerifyingNFT public vnft;

    constructor() ERC721("MyNFT", "MNFT") {
        vnft = new VerifyingNFT(address(this));
    }
}
```

This is my assumed hierarchy. I confirmed a successful deployment after getting the `bytecode` and `abi` of the `MyNFT` contract, and deploying it as follows:

```py
In [6]: my_nft = w3.eth.contract(abi=mnft["abi"], bytecode=mnft["bin"])
In [7]: my_nft.constructor().transact({"from": w3.eth.accounts[0]})
Out[7]: HexBytes('0xbe1a5b8606a8bd4b52946a87fa9ddb55c98a61f6c74fed0084c5bdb17710d0d4')

# check vnft var with deployment address from txn
In [10]: deployed_mnft = w3.eth.contract(address="0xF2E246BB76DF876Cef8b38ae84130F4F55De395b", abi=mnft["abi"])
In [11]: deployed_mnft.functions.vnft().call()
Out[11]: '0x4F9DA333DCf4E5A53772791B95c161B2FC041859'
```

I'm assuming you did not have the proper ABI set up for the contract since that's where the information comes from about whether an argument is passed into the constructor method or not.
