### ISSUE TITLE
signature messageHash do not match sha3

### ISSUE THREAD

**Issue by jfdelgad** [ethereum/web3.py#786] opened 2018-04-23 23:54 UTC
* Version: 4.1
* Python: 3.5
* OS: win

### What was wrong?
The `messageHash` obtained when signing a message does not match with sha3 nor with Keccak256 in solidity.

I have this message
`message = "0xa905556532f8353195f389824fa34ea8f9719519/1000000/1524518223"`

and sign it doing
`signature = w3.eth.account.sign(message_text = message, private_key = account.privateKey)`

the sha3 of the message is 
`w3.sha3(text=message)` and gives HexBytes('0xb5ea9f47d1623c34fff6a20f1159ba75aea1b45129dd8041fe3805d5c71538b9')
the same result is obtained in solidity.

But  `signature.messageHash` is:
HexBytes('0xec307861218311e48d875d3c5e18229225fac3f1db73be2305666329f22f3817')

### How can it be fixed?

I have no idea what is going on here

**Comment by carver** [comment] 2018-04-24 00:18
Potentially a couple of things going on, but one of them is that the hash of the message isn't simply the keccak256, there are other things added first. See https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

Not a bug, so I'm closing, but feel free to continue commenting here for help (and/or check out https://ethereum.stackexchange.com ).

**Closed by carver** 2018-04-24 00:18 UTC
