### ISSUE TITLE
gethdev AutoProvider does not consider the WEB3_PROVIDER_URI environment variable

### ISSUE THREAD

**Issue by Morgon** [ethereum/web3.py#1817] opened 2020-12-23 05:41 UTC
* Version: 5.13.0
* Python: 3.8.5
* OS: Linux (Ubuntu 20.04.1 LTS)

### What was wrong?

When using `web3.auto.gethdev`, the `WEB3_PROVIDER_URI` environment variable does not appear to be honored.

```
$ export WEB3_PROVIDER_URI=file:///path/to/node/geth.ipc

$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3.auto.gethdev import w3
>>> w3.eth.filter({'fromBlock': 'latest'})

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<path>/.local/lib/python3.8/site-packages/web3/eth.py", line 491, in filter
    _filter_id = self.web3.manager.request_blocking(
  File "/<path>/.local/lib/python3.8/site-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/<path>/.local/lib/python3.8/site-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/<path>/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/<path>/.local/lib/python3.8/site-packages/web3/providers/ipc.py", line 234, in make_request
    with self._lock, self._socket as sock:
  File "/<path>/.local/lib/python3.8/site-packages/web3/providers/ipc.py", line 55, in __enter__
    raise FileNotFoundError("cannot connect to IPC socket at path: %r" % self.ipc_path)
FileNotFoundError: cannot connect to IPC socket at path: None
```

### How can it be fixed?

Apply this environment variable to the gethdev autoprovider.

**Comment by kclowes** [comment] 2021-01-05 22:06
Thanks for the report! I'll take a look.

**Comment by AngelGris** [comment] 2021-02-05 19:21
I think the issue is not related to the env vars.
The real problem is that get_default_ipc_path() is returning None because the user doesn't have the geth.ipc in the expected location.
I would be glad to contribute with a fix for this, but I'll need some guidance on what the way to go is.
Would it be the best to raise an exception with an adequate message when get_default_ipc_path() returns None?

**Comment by kclowes** [comment] 2021-02-08 17:45
@AngelGris A PR would be great! I think the reported problem is an environment variable issue, although it's you're right in seeing that if the path doesn't exist, `None` gets returned. I think it would be good to add an error message instead of just silently not connecting, although I'm not sure what the thinking was originally to return None instead of an error. 

I'd approach the env var fix by adding a check at the top of `get_dev_ipc_path` [here](https://github.com/ethereum/web3.py/blob/master/web3/providers/ipc.py#L159) for the environment variable, and then if the path doesn't exist, we can do the `sys.platform` check. So something like:

```
if os.environ.get('WEB3_PROVIDER_URI'):
    if os.path.exists(ipc_path):
        return ipc_path
elif sys.platform == 'dawin':
    ...
```
And then if you're up for it, I'd open a second PR to raise an error if `os.path.exists` returns `False`, since it's technically a breaking change. 

That way, if they're in separate PRs, we can get the environment variable fix in and then talk about whether we want to pull the error change into v5 or start on a v6 branch. The breaking change would only apply to the gethdev auto provider, so I think it would probably be fine to add the error change into v5 but someone else may have a stronger opinion. I also think if we're raising an error when one provider fails to connect, we should probably do it with all of them, but I'd definitely want to wait until v6 to start mucking around with breaking changes in the other providers.

Let me know if anything was unclear or if you have any other questions!

**Comment by Harmouch101** [comment] 2021-05-04 19:38
From my understanding, web3.auto.gethdev would call [get_default_ipc_path](https://github.com/ethereum/web3.py/blob/06803e26903e4f8d94e4a6db7f98a56988664f6a/web3/providers/ipc.py#L82) because of the [IPCProvider](https://github.com/ethereum/web3.py/blob/06803e26903e4f8d94e4a6db7f98a56988664f6a/web3/auto/gethdev.py#L12) call which, in its turn, would call [get_default_ipc_path](https://github.com/ethereum/web3.py/blob/06803e26903e4f8d94e4a6db7f98a56988664f6a/web3/providers/ipc.py#L215) that returns a [string](https://github.com/ethereum/web3.py/blob/master/web3/providers/ipc.py#L82) object that represents the absolute path for the 'jsonrpc.ipc' or the 'geth.ipc' file on the machine. Since the method doesn't handle the case of non existing file, it will return a None type object. Therefore, you need to check if 'geth.ipc' or `jsonrpc.ipc` exist first.

```sh
$ locate geth.ipc
/home/<USER>/.ethereum/geth.ipc

$ locate jsonrpc.ipc
/home/<USER>/.local/share/io.parity.ethereum/jsonrpc.ipc
/home/<USER>/.local/share/trinity/mainnet/ipcs-eth1/jsonrpc.ipc  # <--- running a trinity client will generate this file i guess?
```

Additionally, I think @AngelGris is right by his comment that the problem is not related to the env variable, but rather to a non-existing file.

**Comment by Harmouch101** [comment] 2021-05-06 18:57
@Morgon, to help you with your situation, follow the steps below:

1. Begin by starting your ethereum node such as [Geth](https://geth.ethereum.org/docs/install-and-build/installing-geth#install-on-ubuntu-via-ppas) server by running the following cmd:

```sh
$ geth console # this will generate a geth.ipc file when the node starts up
```

2. Open another terminal, and set the env variable:

```sh
$ export WEB3_PROVIDER_URI=/home/<USER>/.ethereum/geth.ipc  # <--- replace <USER> by your actual user.
```

3.  And then proceed with the python statements.

```python
>>> from web3.auto.gethdev import w3
>>> w3.eth.filter({'fromBlock': 'latest'})
<web3._utils.filters.LogFilter object at 0x7fd9f2bd3850>
```

**Comment by Morgon** [comment] 2021-06-10 19:14
As another test, I `touch`ed `~/.ethereum/geth.ipc` so that we wouldn't get a file not found error. Executing through gethdev showed 'Connection Refused'

This confirms my claim that `WEB3_PROVIDER_URI` is not being honored at all and it's simply looking for the default path.

**Closed** 2021-06-14 16:50 UTC
Labels: Good First Issue, priority: p3 normal
