### ISSUE TITLE
Web3.py installation Issue in Windows 7

### ISSUE THREAD

**Issue by mandritac** [ethereum/web3.py#810] opened 2018-05-04 06:39 UTC
* Version: latest code base from github
* Python: 3.6
* OS: win 7

### What was wrong?

While trying to install Web3.py we are getting the below error at last stage:

```
Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\U
sers\\256558\\AppData\\Local\\Temp\\pip-build-kwrpx614\\cytoolz\\setup.py';f=get
attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" install --record C:\Users\256558\App
Data\Local\Temp\pip-_qeq9_4z-record\install-record.txt --single-version-external
ly-managed --compile" failed with error code 1 in C:\Users\256558\AppData\Local\
Temp\pip-build-kwrpx614\cytoolz\
```

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error 
PFA the log file
[Error.txt](https://github.com/ethereum/web3.py/files/1973434/Error.txt)

* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by voith** [comment] 2018-05-04 06:56
You need Microsoft Visual C++ Build Tools installed on your machine. Your error message points you the link from where you can download them.
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
```
Retry installing web3 after you finish installing them in a new terminal.

This is something that needs to be documented and I will do that soon.

**Comment by mandritac** [comment] 2018-05-04 11:03
I already had installed Microsoft Visual Studio Professional 2017 in my system prior to running the pip install option. 
On my system: VS140COMNTOOLS=**:\Microsoft Visual Studio 14.0\Common7\Tools\ but still it is not working, also I understand this is a trial edition so the trial has expired on my system. Can that be an issue? Which one should I install from - https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017?__hstc=268264337.38ee79ff3839be55fda36125f39e4649.1525342730862.1525349273987.1525431446996.4&__hssc=268264337.1.1525431446996&__hsfp=868344121? 

Thanks.

**Comment by voith** [comment] 2018-05-04 11:18
@mandritac I am not a windows user. However, the last time I tried I installed https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017. 

> I already had installed Microsoft Visual Studio Professional 2017

Please note that Microsoft Visual C++ Build Tools should not be confused with  Microsoft Visual Studio Professional IDE. These are two different things. I made the same mistake in my first attempt. 
However, the IDE should be shipping the build tools along but that didn't work for me.
In fact I had to uninstall the IDE completely because it was creating some path conflicts. I didn't bother  to find out the cause though.

**Comment by mandritac** [comment] 2018-05-04 11:40
Hi the above python snippet raised the error -   File "**:\Python\lib\distutils\msvc9compiler.py", line 262, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
>>>
I am currently uninstall Microsoft Visual Studio 2015 and will try reinstalling the build tool by running - vs_buildtools__986798620.1525342714.exe which is also failing on my system. In the meantime I also have a Oracle Linux Server 7.x version where python is installed. Can I install web3 there?

Thanks.

**Comment by voith** [comment] 2018-05-04 11:48
> raise DistutilsPlatformError("Unable to find vcvarsall.bat")

This is another error that you get when build tools aren't installed properly!

> In the meantime I also have a Oracle Linux Server 7.x version where python is installed. Can I install web3 there?

Ideally you should be create a new `virtualenv` and install web3 in it.

**Comment by mandritac** [comment] 2018-05-04 12:26
I am unable to install the build tool also, the installer exits with the error - *\ProgramData\Microsoft\VisualStudio\Packages\_bootstrapper\vs_setup_bootstrapper_201805041751089371.json' is denied.
When I checked the folder there is no  json file at all it is trying to access, so is there any pre-requisite prior installing the build tools?

Also about virtualenv, doesn't not require Microsoft build tools?
Thanks.

**Comment by voith** [comment] 2018-05-04 12:42
> I am unable to install the build tool

As much as I'd like to help you, I'm not a windows user. So asking for help on stackexchange might be better. 

> \ProgramData\Microsoft\VisualStudio\Packages_bootstrapper\vs_setup_bootstrapper_201805041751089371.json' is denied.

However, looking at your `is denied` error I would check if I have the right privileges to install it. Probably use Administrator access to install the binary.

>  Also about virtualenv, doesn't not require Microsoft build tools?

No, virtualenv just makes sure that you don't have library conflicts between packages used by different projects. You'd need build tools for building libraries that use `c extensions`

**Comment by mandritac** [comment] 2018-05-04 12:50
No even with virtual env nothing improved, error remains the same -     
building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

So I guess this thing doesn't work without a proper installation of the c++ build tool.

    ----------------------------------------

**Comment by pipermerriam** [comment] 2018-05-04 15:30
Correct, you will need the ability to compile c extensions to be able to install web3.py.  Since this doesn't appear to be a problem with web3.py I'm closing this but feel free to continue the conversation here.

**Closed by pipermerriam** 2018-05-04 15:30 UTC

**Comment by abhi3700** [comment] 2021-06-30 20:47
Solution:
1. Try this:
```
$ conda install libpython m2w64-toolchain -c msys2
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - libpython
    - m2w64-toolchain


The following NEW packages will be INSTALLED:

  libpython          pkgs/main/win-64::libpython-2.1-py38_0
  m2w64-binutils     msys2/win-64::m2w64-binutils-2.25.1-5
  m2w64-bzip2        msys2/win-64::m2w64-bzip2-1.0.6-6
  m2w64-crt-git      msys2/win-64::m2w64-crt-git-5.0.0.4636.2595836-2
  m2w64-gcc          msys2/win-64::m2w64-gcc-5.3.0-6
  m2w64-gcc-ada      msys2/win-64::m2w64-gcc-ada-5.3.0-6
  m2w64-gcc-fortran  msys2/win-64::m2w64-gcc-fortran-5.3.0-6
  m2w64-gcc-objc     msys2/win-64::m2w64-gcc-objc-5.3.0-6
  m2w64-headers-git  msys2/win-64::m2w64-headers-git-5.0.0.4636.c0ad18a-2
  m2w64-isl          msys2/win-64::m2w64-isl-0.16.1-2
  m2w64-libiconv     msys2/win-64::m2w64-libiconv-1.14-6
  m2w64-libmangle-g~ msys2/win-64::m2w64-libmangle-git-5.0.0.4509.2e5a9a2-2
  m2w64-make         msys2/win-64::m2w64-make-4.1.2351.a80a8b8-2
  m2w64-mpc          msys2/win-64::m2w64-mpc-1.0.3-3
  m2w64-mpfr         msys2/win-64::m2w64-mpfr-3.1.4-4
  m2w64-pkg-config   msys2/win-64::m2w64-pkg-config-0.29.1-2
  m2w64-toolchain    msys2/win-64::m2w64-toolchain-5.3.0-7
  m2w64-tools-git    msys2/win-64::m2w64-tools-git-5.0.0.4592.90b8472-2
  m2w64-windows-def~ msys2/win-64::m2w64-windows-default-manifest-6.4-3
  m2w64-winpthreads~ msys2/win-64::m2w64-winpthreads-git-5.0.0.4634.697f757-2
  m2w64-zlib         msys2/win-64::m2w64-zlib-1.2.8-10

The following packages will be UPDATED:

  conda                                4.9.2-py38haa95532_0 --> 4.10.1-py38haa95532_1
```
1. `pip install web3`

Your installation is done successfully.

**Comment by browolf** [comment] 2022-04-03 13:44
can i uninstall VS build tools after  installing web3?
