### ISSUE TITLE
Events being included in logs from two different blocks only when filtering for events from block ranges of size 1

### ISSUE THREAD

**Issue by SpencerMiller23** [ethereum/web3.py#2761] opened 2022-12-15 08:07 UTC
* Version: 6.0.0b3
* Python: 3.10.4
* OS: linux/win
* `pip freeze` output

```
aiohttp==3.8.3
aiosignal==1.3.1
async-timeout==4.0.2
attrs==22.1.0
base58==2.1.1
bitarray==1.2.2
certifi==2022.12.7
charset-normalizer==2.1.1
cytoolz==0.12.0
eth-abi==3.0.1
eth-account==0.6.1
eth-hash==0.5.1
eth-keyfile==0.6.0
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.2.0
eth-utils==2.1.0
frozenlist==1.3.3
hexbytes==0.3.0
idna==3.4
ipfshttpclient==0.8.0a2
jsonschema==4.17.3
lru-dict==1.1.8
multiaddr==0.0.9
multidict==6.0.3
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.20.3
pycryptodome==3.16.0
pyrsistent==0.19.2
pywin32==305
requests==2.28.1
rlp==3.0.0
six==1.16.0
toolz==0.12.0
urllib3==1.26.13
varint==1.0.2
web3==6.0.0b3
websockets==10.4
yarl==1.8.2
```

### What was wrong?

Due to version conflicts in the codebase, I ended up having to use the above version. I have a script which continuously filters for events on each block as they are included in the chain. I noticed that every event is being returned twice: once in the search of the block **before** it was emitted and once in the block that it was emitted. I observed that this behaviour occurs only when the range of blocks that are being filtered is of size 1. I confirmed this by running the included sample code.

```
from web3 import Web3
from web3.middleware import geth_poa_middleware
from web3._utils.filters import Filter

def filter_events(w3, start_block, end_block):
    event_filter: Filter = w3.eth.filter({
    'address': ['0x5EE094C36B9ae110ddd10F10A770d288316369B6'],
    'topics': [['0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f']],
    'fromBlock': start_block,
    'toBlock': end_block
    })

    return event_filter.get_all_entries()

if __name__ == '__main__':
    w3 = Web3(Web3.HTTPProvider('https://matic-mumbai.chainstacklabs.com'))
    w3.middleware_onion.inject(geth_poa_middleware, layer=0)

    # EXPECTED logs to be for block 29683376 only (Got 29683376 and 29683377)
    print(filter_events(w3, 29683376, 29683377))

    # EXPECTED logs to be for block 29683377 only (GOT 29683377 and 29683378)
    print(filter_events(w3, 29683377, 29683378))

    # GOT logs include blocks 29683375 and 29683376 only
    print(filter_events(w3, 29683375, 29683377))

    # GOT logs include block 29683376 and 29683377 only
    print(filter_events(w3, 29683376, 29683378))
```

### How can it be fixed?

I'm not sure how to fix it but as far as I know, the expected behaviour is that the events returned should be from blocks `fromBlock` until `toBlock - 1`

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment] 2022-12-15 18:04
> the expected behaviour is that the events returned should be from blocks fromBlock until toBlock - 1 

Just curious, where did you get your expected behavior details from? How would that work if `toBlock` is `latest`? You'd never get events from the latest block if it's non-inclusive. Also, how does that work if `fromBlock` is the same as `toBlock`? As far as I know that doesn't return an error from any provider implementation and that's the way to pick out a single block for events.

Using your above example, block number `29683376` has no events so using `fromBlock=29683376` and `toBlock=`29683377` only returns events from block `29683377`; as does using `29683377` as both the `fromBlock` and `toBlock`. 

I can't reproduce what you are seeing on my end using the same script you posted here. If you think there is still an error here let's re-open but I'm going to close this for now as I don't see an issue here.

Source for details: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_newfilter

**Closed by fselmo** 2022-12-15 18:04 UTC

**Comment by fselmo** [comment] 2022-12-15 18:10
Also, I forgot to address why you're seeing two logs. You are creating a new filter each time. 

The event filter need only be created once:

```py
event_filter: Filter = w3.eth.filter({
    'address': ['0x5EE094C36B9ae110ddd10F10A770d288316369B6'],
    'topics': [['0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f']],
    'fromBlock': start_block,
    'toBlock': end_block
    })
```

and you get new entries by calling

```py
event_filter.get_all_entries()
```

**Comment by fselmo** [comment] 2022-12-15 18:19
I meant to edit my last comment, but I'm actually not seeing two events and I am getting some errors trying to runt he script exactly how it is written. If you are indeed getting two of the same event then that is definitely strange. I'll take a closer look at this example and get back. If you have the response, can you share it here?

**Comment by fselmo** [comment] 2022-12-15 18:37
Yeah, can't reproduce. I only see one event, from block number `29683377`, which is returned in every example you named and never is it returned twice. I'll just leave my results here for reference.


With this setup:

```py
w3 = Web3(Web3.HTTPProvider('https://matic-mumbai.chainstacklabs.com'))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

def create_filter(w3, start_block, end_block):
    event_filter = w3.eth.filter({
        'address': ['0x5EE094C36B9ae110ddd10F10A770d288316369B6'],
        'topics': [['0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f']],
        'fromBlock': start_block,
        'toBlock': end_block
    })
    return event_filter
```

And these outputs from ipy:

```py
# 29683376 to 29683377

In [1]: six_seven = create_filter(w3, 29683376, 29683377)
In [2]: six_seven.get_all_entries()
Out[2]: 
[AttributeDict({'address': '0x5EE094C36B9ae110ddd10F10A770d288316369B6',
  'topics': [HexBytes('0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f'),
   HexBytes('0x00000000000000000000000010f439548897414baeb97ac84e0c450204aff78d'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000001'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000005')],
  'data': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000029000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000c0e70c8c4ead421d1323dbc1cbb6147d02e75f6570c221c4dab297c45c11d3904a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666234313063333665663663646639363963346235313662316535613762666262396130343062343632626261316338333839666666376365633239313635646536663661303663386465346364643539653938663434633762646261633864356632316164340000000000000000000000000000000000000000000000000000'),
  'blockNumber': 29683377,
  'transactionHash': HexBytes('0x4ca7e38bbd1d17c1fc2edbc1f4389b7bfd390e0317325fa022f4a1acdca380ea'),
  'transactionIndex': 1,
  'blockHash': HexBytes('0x17d2208b5eda0b1552f6670b76beda6932a8b351ea427510b9c5d5cb4bf3de83'),
  'logIndex': 10,
  'removed': False})]
  
# 29683377 to 29683378

In [3]: seven_eight = create_filter(w3, 29683377, 29683378)
In [4]: seven_eight.get_all_entries()
Out[4]: 
[AttributeDict({'address': '0x5EE094C36B9ae110ddd10F10A770d288316369B6',
  'topics': [HexBytes('0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f'),
   HexBytes('0x00000000000000000000000010f439548897414baeb97ac84e0c450204aff78d'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000001'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000005')],
  'data': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000029000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000c0e70c8c4ead421d1323dbc1cbb6147d02e75f6570c221c4dab297c45c11d3904a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666234313063333665663663646639363963346235313662316535613762666262396130343062343632626261316338333839666666376365633239313635646536663661303663386465346364643539653938663434633762646261633864356632316164340000000000000000000000000000000000000000000000000000'),
  'blockNumber': 29683377,
  'transactionHash': HexBytes('0x4ca7e38bbd1d17c1fc2edbc1f4389b7bfd390e0317325fa022f4a1acdca380ea'),
  'transactionIndex': 1,
  'blockHash': HexBytes('0x17d2208b5eda0b1552f6670b76beda6932a8b351ea427510b9c5d5cb4bf3de83'),
  'logIndex': 10,
  'removed': False})]

# 29683375 to 29683377

In [5]: five_seven = create_filter(w3, 29683375, 29683377)
In [6]: five_seven.get_all_entries()
Out[6]: 
[AttributeDict({'address': '0x5EE094C36B9ae110ddd10F10A770d288316369B6',
  'topics': [HexBytes('0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f'),
   HexBytes('0x00000000000000000000000010f439548897414baeb97ac84e0c450204aff78d'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000001'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000005')],
  'data': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000029000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000c0e70c8c4ead421d1323dbc1cbb6147d02e75f6570c221c4dab297c45c11d3904a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666234313063333665663663646639363963346235313662316535613762666262396130343062343632626261316338333839666666376365633239313635646536663661303663386465346364643539653938663434633762646261633864356632316164340000000000000000000000000000000000000000000000000000'),
  'blockNumber': 29683377,
  'transactionHash': HexBytes('0x4ca7e38bbd1d17c1fc2edbc1f4389b7bfd390e0317325fa022f4a1acdca380ea'),
  'transactionIndex': 1,
  'blockHash': HexBytes('0x17d2208b5eda0b1552f6670b76beda6932a8b351ea427510b9c5d5cb4bf3de83'),
  'logIndex': 10,
  'removed': False})]

# 29683376 to 29683378

In [7]: six_eight = create_filter(w3, 29683376, 29683378)
In [8]: six_eight.get_all_entries()
Out[8]: 
[AttributeDict({'address': '0x5EE094C36B9ae110ddd10F10A770d288316369B6',
  'topics': [HexBytes('0xa09dd32955694000e96fcafeba044b4dbd4850f23f8ab83a94833731fc9e947f'),
   HexBytes('0x00000000000000000000000010f439548897414baeb97ac84e0c450204aff78d'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000001'),
   HexBytes('0x0000000000000000000000000000000000000000000000000000000000000005')],
  'data': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000029000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000c0e70c8c4ead421d1323dbc1cbb6147d02e75f6570c221c4dab297c45c11d3904a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000666234313063333665663663646639363963346235313662316535613762666262396130343062343632626261316338333839666666376365633239313635646536663661303663386465346364643539653938663434633762646261633864356632316164340000000000000000000000000000000000000000000000000000'),
  'blockNumber': 29683377,
  'transactionHash': HexBytes('0x4ca7e38bbd1d17c1fc2edbc1f4389b7bfd390e0317325fa022f4a1acdca380ea'),
  'transactionIndex': 1,
  'blockHash': HexBytes('0x17d2208b5eda0b1552f6670b76beda6932a8b351ea427510b9c5d5cb4bf3de83'),
  'logIndex': 10,
  'removed': False})]
```
