### ISSUE TITLE
Insufficient funds no matter what (error -32000)

### ISSUE THREAD

**Issue by nazariyv** [ethereum/web3.py#1659] opened 2020-05-21 20:00 UTC
* Version: 5.10.0
* Python: 3.7.7
* OS: osx
* `pip freeze` output

```
appnope==0.1.0
attrs==19.3.0
backcall==0.1.0
base58==2.0.0
bitarray==1.2.2
bleach==3.1.5
certifi==2020.4.5.1
chardet==3.0.4
cytoolz==0.10.1
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.2
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.1.2
eth-typing==2.2.1
eth-utils==1.9.0
hexbytes==0.2.0
idna==2.9
importlib-metadata==1.6.0
ipfshttpclient==0.4.13.2
ipykernel==5.3.0
ipython==7.14.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
lru-dict==1.1.6
MarkupSafe==1.1.1
mistune==0.8.4
multiaddr==0.0.9
nbconvert==5.6.1
nbformat==5.0.6
netaddr==0.7.19
notebook==6.0.3
numpy==1.18.4
packaging==20.4
pandas==1.0.3
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.12.1
ptyprocess==0.6.0
pycryptodome==3.9.7
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
requests==2.23.0
rlp==1.2.0
Send2Trash==1.5.0
six==1.14.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
traitlets==4.3.3
typing-extensions==3.7.4.2
urllib3==1.25.9
varint==1.0.2
wcwidth==0.1.9
web3==5.10.0
webencodings==0.5.1
websockets==8.1
widgetsnbextension==3.5.1
zipp==3.1.0
```

### What was wrong?

```
from web3.auto.infura import w3

transaction = {
    'to': '0x465DCa9995D6c2a81A9Be80fBCeD5a770dEE3daE',
    'value': 1000,
    'gas': 2000000,
    'gasPrice': 20000000000,
    'nonce': 0,
    'chainId': 1,
}

signed_tx = w3.eth.account.sign_transaction(transaction, priv_key)

w3.eth.sendRawTransaction(signed_tx.rawTransaction)  
```

and then I get this

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-126-a30720cb9cc3> in <module>
----> 1 w3.eth.sendRawTransaction(signed_tx.rawTransaction)

~/v/ecc/lib/python3.7/site-packages/web3/eth.py in sendRawTransaction(self, raw_transaction)
    390         return self.web3.manager.request_blocking(
    391             RPC.eth_sendRawTransaction,
--> 392             [raw_transaction],
    393         )
    394 

~/v/ecc/lib/python3.7/site-packages/web3/manager.py in request_blocking(self, method, params, error_formatters)
    151         if "error" in response:
    152             apply_error_formatters(error_formatters, response)
--> 153             raise ValueError(response["error"])
    154 
    155         return response['result']

ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

`w3.eth.getBalance("0xd93800B7290B37a3ac36e4cDd3F881a929acD4A3")`

is the address from which I am sending, and it has enough ether on it. Very perplexed about this

### How can it be fixed?

??

**Comment by marcgarreau** [comment] 2020-05-21 20:19
Without digging in too much, first guess is that you have a [defaultAccount](https://web3py.readthedocs.io/en/stable/web3.eth.html?highlight=defaultAccount#web3.eth.Eth.defaultAccount) set to something other than this address. Let me know if that is or is not helpful.

**Comment by nazariyv** [comment] 2020-05-21 20:47
I think you are right! How do I change it? Do I just directly write `Eth.defaultAccount = "0xd93800B7290B37a3ac36e4cDd3F881a929acD4A3"?`

**Comment by marcgarreau** [comment] 2020-05-21 20:52
Great! Yup - within a Web3 instance it's available on the `eth` namespace, e.g., `w3.eth.defaultAccount = "0x..."`

**Comment by nazariyv** [comment] 2020-05-22 08:09
So, adding the `from` field and then attempting to send causes same error. Overriding the default account with `w3.eth.defaultAccount = 'checksummedaddressfrom'` doesn't work. And having both doesn't work.  🤔

**Comment by nazariyv** [comment] 2020-05-22 08:10
Does the private key need to be in a special form? Mine is not check summed (not sure if it applies to private keys) and in hexadecimal form.

**Comment by nazariyv** [comment] 2020-05-23 16:02
@marcgarreau sorry for atting, but do you have any other clues about how I can resolve this? thanks

**Comment by marcgarreau** [comment] 2020-05-26 17:15
@nazariyv Apologies, I think I steered you wrong initially. I don't believe the address sending the raw transaction should make any difference, as long as the account that's signed the tx has sufficient funds.

Doing some testing locally, I am able to reproduce this exception when I wouldn't expect to:
<img width="912" alt="Screen Shot 2020-05-26 at 11 12 22 AM" src="https://user-images.githubusercontent.com/3621728/82930003-de54a000-9f41-11ea-8863-ca8cefd091e6.png">

However, if I remove a zero from that gas amount (e.g., from 2,000,000 to 200,000), the transaction is successful. So, short-term solution: you can try to lowering the gas amount to something appropriate for your use case. Simple transfers of ETH are 21,000 gas; deployments of or interactions with contracts are larger and more variable.

Beyond that, I'll have to dig in further.

**Comment by pipermerriam** [comment] 2020-05-26 17:26
@marcgarreau I'm not sure there's a trivial way to do this but we *might* be able to add some special casing code to `eth_sendTransaction` and `eth_sendRawTransaction` calls that raises a more user friendly error in this case.

The problem is that we won't actually have a good way to detect this error without doing something gross like matching the error string.  Still, upon hitting an error to either of these JSON-RPC APIs we could do a quick check for whether `w3.eth.getBalance(addr) >= txn.gas * txn.gas_price + txn.value` and if not, re-raise with a more descriptive error message that includes the address, the balance of the address, and the breakdown of total cost of the transaction itself.

**Comment by marcgarreau** [comment] 2020-05-26 17:47
Definitely room for better error handling in that regard, but in my testing, the sending account is a `geth --dev` account that shouldn't be anywhere close to not being able to afford the tx:
```
gas * price + value = 40000000000001000 
balance = 115792089237316195423570985008687907853269984665640564039457574012113129639928
```

**Comment by pipermerriam** [comment] 2020-05-26 18:10
:+1: so something else happening beyond simple insufficient balance... interesting.

**Comment by marcgarreau** [comment] 2020-05-26 21:42
False alarm. I'm not able to reproduce the issue again, so I think the more likely scenario is that I was juggling too many accounts and the private key indeed belonged to an account with insufficient funds.

Specific to @nazariyv, I finally did the math and this is just a case of insufficient funds. The mentioned address has 0.011 ETH and the cost of the transaction is 0.04 ETH. So, the solution is to dial in the gas number. (Maybe we should tweak the examples to use a standard tx fee instead of [2MM](https://web3py.readthedocs.io/en/latest/web3.eth.account.html?highlight=sign#sign-a-transaction) and/or provide some of this context). 

Re: error message enhancements, possibly the `sign_transaction` request could return an exception or warning if its balance is insufficient, but seems overkill to disallow tx signing by accounts prior to being funded. Tl;dr - I think the existing exception is sufficient.

Closing this issue; please reopen or add further comment if you still need assistance @nazariyv :v:

**Closed by marcgarreau** 2020-05-26 21:42 UTC

**Comment by OkarFabianTheWise** [comment] 2023-02-09 09:36
Okay with all the errors above ,I can boldly state with experience that it is beyond balance.

With 3$ worth of BNB in my wallet ,I can swap 2$ worth for a token on pancakeswap and pay a gas fee of 0.4$ worth of BNB..
But it fails with web3py.

gas: 400000
gasPrice: 10 gwei

**Comment by vigneshbalu96** [comment] 2024-12-02 23:39
I'm facing the same Error but my Anvil chain has enough funds to process a transaction in foundry...

> vicky:~/foundry-f24/Raffle_Smart_Contract_F24$ forge script script/Interactions.s.sol:FundSubscription --rpc-url $SEPOLIA_RPC_URL --account default --broadcast -vvvv

(Before the error prompt Everything seems Cool 😄 )
(Error prompts at the end 👇 )
Error:
Failed to send transaction

Context:

server returned an error response: error code -32000: insufficient funds for gas * price + value: balance 10, tx cost 1226346447223926, overshot 1226346447223916.
Cheers!
