### ISSUE TITLE
Event filter get_all_entries() hangs on waiter.acquire()

### ISSUE THREAD

**Issue by osolmaz** [ethereum/web3.py#1062] opened 2018-09-17 17:17 UTC
* Version: 4.7.1
* Python: 3.7
* OS: Manjaro Linux

I'm using a filter to get the events for blocks 6191609 to 6191909 for a contract. Here is the code

```python
from web3 import Web3
import requests
import json

ABI_REQUEST_ENDPOINT = 'https://api.etherscan.io/api?module=contract&action=getabi&address='

def etherscan_fetch_abi(addr):
    response = requests.get('%s%s'%(ABI_REQUEST_ENDPOINT, addr))
    response_json = response.json()
    abi = json.loads(response_json['result'])
    return abi

addr = Web3.toChecksumAddress('0xa62142888aba8370742be823c1782d17a0389da1')

provider = Web3.WebsocketProvider('wss://mainnet.infura.io/ws/')
w3 = Web3(provider)

start_block = 6191609
end_block = 6191909

contract_abi = etherscan_fetch_abi(addr)

contract = w3.eth.contract(addr, abi=contract_abi)

filters = {}
for i in contract.events._events:
    name = i['name']
    filters[name] = contract.events.__dict__[name].createFilter(fromBlock=start_block, toBlock=end_block)

block_event_dict = {}
for i in range(start_block, end_block+1):
    block_event_dict[i] = {}

for event_name, filter_ in filters.items():
    print('Getting %s events'%event_name)
    entries = filter_.get_all_entries()
```

The program hangs on the second event. I get the following when I run `Ctrl+C`

```
Traceback (most recent call last):
  File "plot_events.py", line 140, in <module>
    __main__()
  File "plot_events.py", line 66, in __main__
    entries = filter_.get_all_entries()
  File "/usr/lib/python3.7/site-packages/web3/utils/filters.py", line 112, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/usr/lib/python3.7/site-packages/web3/eth.py", line 349, in getFilterLogs
    "eth_getFilterLogs", [filter_id],
  File "/usr/lib/python3.7/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/lib/python3.7/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.7/site-packages/web3/providers/websocket.py", line 104, in make_request
    return future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 427, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

Do you have any idea why it hangs?

**Comment by osolmaz** [comment] 2018-09-17 17:29
> Does it hang when you request entries for the specific event that is hanging?

Yes it hangs when I filter only the event that hangs. 

>  Are there many logs for that that event that could be causing the hang?

How can I see the logs?

> Have you tried limiting the block range?

It doesn't hang for 100 blocks, but it does for >200.

**Comment by dylanjw** [comment] 2018-09-17 17:32
It is likely an issue with infura's response size being too large.  Try splitting up the block range and making a series of smaller requests.

**Comment by voith** [comment] 2018-09-17 17:38
@osolmaz might be related to https://github.com/ethereum/web3.py/issues/913
Try:
```python
w3 = Web3(Web3.WebsocketProvider(max_size=SOME_LARGE_NUMBER))
```

**Comment by osolmaz** [comment] 2018-09-17 17:46
@voith `WebsocketProvider` constructor doesn't appear to have a `max_size` argument.

**Comment by voith** [comment] 2018-09-17 17:49
@osolmaz sorry about that. updated my comment

**Comment by osolmaz** [comment] 2018-09-17 17:52
@voith I tried 

```
provider = Web3.WebsocketProvider('wss://mainnet.infura.io/ws/', websocket_kwargs={'max_size': 100000000000000})
```

It still hangs

**Comment by voith** [comment] 2018-09-17 20:50
@osolmaz I just tested this with `wscat`. Here are the results:
If I use a small batch (`start_block = 6191609`, `end_block = 6191709`), then it works:
```
➜  ~ wscat -c wss://mainnet.infura.io/ws
connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","method":"eth_newFilter","params":[{"fromBlock": "0x5e79f9", "toBlock": "0x5e7a5d", "address": "0xA62142888ABa8370742bE823c1782D17A0389Da1"}],"id": 1}
< {"jsonrpc":"2.0","id":1,"result":"0x2f398298ec17203ce37560997554356c"}

> {"jsonrpc":"2.0","method":"eth_getFilterLogs", "params":["0x2f398298ec17203ce37560997554356c"], "id": 1}
< {"jsonrpc":"2.0","id":1,"result":[{"address":"0xa62142888aba8370742be823c1782d17a0389da1","blockHash":"0x18fa3b85323d669f6b38e0d3d238db542b8c1e51da347a5044950abd15587e49","blockNumber":"0x5e79fe","data":"0x00000000000000000000000000000000000000028b31c684e6808139d8dc0c1c000000000000000000001aba4714957d300d0e549208b31adb100000000052bb0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ada1ed8dea59b7b082937460c0863abffbb0484f00000000000000000000000000000000000000000000000000147c763841882f0000000000000000000000000000000000000000000000000e92596fa9a4db800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000418e471a6b4d6000000000000000000000000000000000000000000000000000b78e6091a76bd000000000000000000000000000000000000000000000000000418e471a6b4d80000000000000000000000000000000000000000000000000565fd6e66c6e267","logIndex":"0x8","removed":false,"topics":["0x500e72a0e114930aebdbcb371ccdbf43922c49f979794b5de4257ff7e310c746"],"transactionHash":"0xfc1e6a60e542d4be9e555a84859ce420a8e1678eb8b51971274c11aa441c034b","transactionIndex":"0x16"},{"address":"0xa62142888aba8370742be823c1782d17a0389da1","blockHash":"0x18fa3b85323d669f6b38e0d3d238db542b8c1e51da347a5044950abd15587e49","blockNumber":"0x5e79fe","data":"0x00000000000000000000000000000000000000028b31c684e6808139d8dc0c1c000000000000000000001aba4714957d300d0e549208b31adb100000000052bb0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ada1ed8dea59b7b082937460c0863abffbb0484f00000000000000000000000000000000000000000000000000147c763841882f0000000000000000000000000000000000000000000000000e9259685bf6cef60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000418e471a6b4d6000000000000000000000000000000000000000000000000000b78e60acce162000000000000000000000000000000000000000000000000000418e471a6b4d8000000000000000000000000000000000000000000000000056631e039426b71","logIndex":"0x36","removed":false,"topics":["0x500e72a0e114930aebdbcb371ccdbf43922c49f979794b5de4257ff7e310c746"],"transactionHash":"0x8a4190f3e042b9e01bfcbde8fc67960a8f56d1003ed52a52b15b24e7b19b9a94","transactionIndex":"0x52"},{"address":"0xa62142888aba8370742be823c1782d17a0389da1","blockHash":"0x18fa3b85323d669f6b38e0d3d238db542b8c1e51da347a5044950abd15587e49","blockNumber":"0x5e79fe","data":"0x00000000000000000000000000000000000000028b31c684e6808139d8dc0c1c000000000000000000001aba4714957d300d0e549208b31adb100000000051b4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060f95d83bca8285b4761bce249c21d7ae149cad5000000000000000000000000000000000000000000000000001382b9f1f3291e0000000000000000000000000000000000000000000000000de0b6cc598984c800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003e6f1fd30a1d2000000000000000000000000000000000000000000000000000aed0bf6d20cf60000000000000000000000000000000000000000000000000003e6f1fd30a1d4000000000000000000000000000000000000000000000000056663d2b91e7388","logIndex":"0x39","removed":false,"topics":["0x500e72a0e114930aebdbcb371ccdbf43922c49f979794b5de4257ff7e310c746"],"transactionHash":"0x66bdb2da6aa47108be3b649d646419e7df18838c6a509bcd0f6433446675f3a1","transactionIndex":"0x53"},{"address":"0xa62142888aba8370742be823c1782d17a0389da1","blockHash":"0x18fa3b85323d669f6b38e0d3d238db542b8c1e51da347a5044950abd15587e49","blockNumber":"0x5e79fe","data":"0x00000000000000000000000000000000000000028b31c684e6808139d8dc0c1c000000000000000000001aba4714957d300d0e549208b31adb100000000052f361797961000000000000000000000000000000000000000000000000000000000000000000000000000000002a9f53e7d95ecd06e6436ce313f1c767320203630000000000000000000000000000000000000000000000000013e69eba669b5d0000000000000000000000000000000000000000000000000e27c483949b18ce00000000000000000000000000000000000000000000000000000000000000000000...
```
If I use a larger batch(`start_block = 6191609`, `end_block = 6191909`), it hangs
```
➜  ~ wscat -c wss://mainnet.infura.io/ws
connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","method":"eth_newFilter","params":[{"fromBlock": "0x5e79f9", "toBlock": "0x5e7b25", "address": "0xA62142888ABa8370742bE823c1782D17A0389Da1"}],"id": 1}
< {"jsonrpc":"2.0","id":1,"result":"0x6b9bd6a290a1ed277b225da1c1df87d"}

> {"jsonrpc":"2.0","method":"eth_getFilterLogs", "params":["0x6b9bd6a290a1ed277b225da1c1df87d"], "id": 1}
> # hangs

```
This is not a bug in `web3.py`. @osolmaz either use a smaller batch size, else complain to `infura`. Feel free to use the test results above to create an issue.

**Comment by carver** [comment] 2018-09-18 00:13
Closing as not a web3.py bug, feel free to continue the conversation here.

**Closed by carver** 2018-09-18 00:13 UTC
