### ISSUE TITLE
w3.isConnected() on Geth testnet is always False

### ISSUE THREAD

**Issue by tJpADUNCcs** [ethereum/web3.py#1050] opened 2018-09-10 09:06 UTC
* Version: 4.6.0
* Python: 3.7
* OS: OSX
* Geth: 1.8.15

Why is the behavior of isConnected() different on Geth testnet compared to mainnet?
In case I use mainnet isConnected() works as expected. In case of using --testnet isConnected() is always False...

    from web3.auto import w3
    if (w3.isConnected()):
        print("I am connected")
    else:
        print("I am not connected")

Anything I need to change on testnet?

**Comment by carver** [comment] 2018-09-10 23:06
The default automatic `w3` instance looks for mainnet. You can set up your own w3 instance to connect to Ropsten, like so:

```py
>>> from web3 import Web3, IPCProvider

# connect to the IPC location started with 'geth --testnet'
>>> w3 = Web3(IPCProvider('~/.ethereum/testnet/geth.ipc'))

>>> from web3.middleware import geth_poa_middleware

# geth's default testnet has a small incompatibility with mainnet API,
# so inject the poa compatibility middleware to the innermost layer
>>> w3.middleware_stack.inject(geth_poa_middleware, layer=0)

# confirm that the connection succeeded
>>> w3.isConnected()
```
~[rough source](https://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority)

---

Closing because it's almost certainly not a bug, but feel free to continue the conversation here.

**Closed by carver** 2018-09-10 23:06 UTC

**Comment by tJpADUNCcs** [comment] 2018-09-15 21:14
@carver thanks for your answer, I tried your code today but isConnected() does still respond False. 
I modified the path to my geth but it is still not working... Any further/additional hints?

Thanks

Simon

**Comment by carver** [comment] 2018-09-17 18:27
Are you able to connect with `geth attach <ipc file path>`? (which uses web3.js) Problems like this are usually something like the wrong file path, or geth has IPC turned off, etc. If you can connect with `geth attach` then it's worth debugging what's happening in web3.py.
