### ISSUE TITLE
Web3.py isConnected returns False in long-living process. How to force reconnect?

### ISSUE THREAD

**Issue by theoden-dd** [ethereum/web3.py#2512] opened 2022-06-15 14:46 UTC
* Version: 5.29.0
* Python: 3.9.10
* OS: linux (in docker)
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
appdirs==1.4.4
appnope==0.1.2
asgiref==3.5.0
astor==0.8.1
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
autorepr==0.3.0
Babel==2.9.1
backcall==0.2.0
bandit==1.7.4
base58==2.1.1
bcrypt==3.2.0
bitarray==1.2.2
blinker==1.4
cached-property==1.5.2
cattrs==1.10.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.0
click-default-group==1.2.2
ConfigUpdater==3.1
coreapi==2.3.3
coreschema==0.0.4
coverage==6.3.2
cryptography==36.0.2
cytoolz==0.11.2
darglint==1.8.1
decorator==5.1.1
defusedxml==0.7.1
dennis==0.9
dictdiffer==0.9.0
Django==3.2.12
django-axes==5.31.0
django-coverage-plugin==2.0.2
django-csp==3.7
django-debug-toolbar==3.2.4
django-extra-checks==0.11.0
django-health-check==3.16.5
django-http-referrer-policy==1.1.1
django-ipware==4.0.2
django-migration-linter==4.0.0
django-permissions-policy==4.9.0
django-querycount==0.7.0
django-split-settings==1.1.0
django-stubs==1.10.1
django-stubs-ext==0.4.0
django-templated-mail==1.1.1
django-test-migrations==1.2.0
djangorestframework==3.13.1
djangorestframework-simplejwt==4.8.0
djoser==2.1.0
doc8==0.11.1
docopt==0.6.2
docutils==0.17.1
dotenv-linter==0.3.0
dparse==0.5.1
dpath==2.0.6
dump-env==1.3.0
eradicate==2.0.0
eth-abi==2.1.1
eth-account==0.5.7
eth-bloom==1.0.4
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
executing==0.8.3
flake8==3.9.2
flake8-bandit==3.0.0
flake8-broken-line==0.4.0
flake8-bugbear==22.3.23
flake8-commas==2.1.0
flake8-comprehensions==3.8.0
flake8-debugger==4.0.0
flake8-django==1.1.2
flake8-docstrings==1.6.0
flake8-eradicate==1.2.0
flake8-isort==4.1.1
flake8-logging-format==0.6.0
flake8-plugin-utils==1.3.2
flake8-polyfill==1.0.2
flake8-pytest-style==1.6.0
flake8-quotes==3.3.1
flake8-rst-docstrings==0.2.5
flake8-string-format==0.3.0
flatten-dict==0.4.2
frozenlist==1.3.0
furl==2.1.3
gitdb==4.0.9
GitPython==3.1.27
gunicorn==20.1.0
hexbytes==0.2.2
hypothesis==6.41.0
identify==2.4.12
idna==3.3
imagesize==1.3.0
importlib-metadata==4.11.3
iniconfig==1.1.1
ipfshttpclient==0.8.0a2
ipython==8.2.0
isort==5.10.1
itypes==1.2.0
jedi==0.18.1
Jinja2==3.1.1
jmespath==1.0.0
jsonschema==3.2.0
loguru==0.6.0
lru-dict==1.1.7
MarkupSafe==2.1.1
marshmallow==3.15.0
marshmallow-polyfield==5.10
matplotlib-inline==0.1.3
mccabe==0.6.1
more-itertools==8.12.0
multiaddr==0.0.9
multidict==6.0.2
mypy==0.942
mypy-extensions==0.4.3
netaddr==0.8.0
nitpick==0.32.0
nplusone==1.0.0
oauthlib==3.2.0
orderedmultidict==1.0.1
packaging==21.3
parsimonious==0.8.1
parso==0.8.3
pathspec==0.9.0
pbr==5.8.1
pep8-naming==0.12.1
pexpect==4.8.0
pickleshare==0.7.5
pluggy==1.0.0
ply==3.11
polib==1.1.1
polint==0.4
prompt-toolkit==3.0.28
protobuf==3.20.0
psycopg2-binary==2.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py-ecc==5.2.0
py-evm==0.5.0a3
py-geth==3.7.0
pycodestyle==2.7.0
pycparser==2.21
pycryptodome==3.14.1
pydocstyle==6.1.1
pyethash==0.1.27
pyflakes==2.3.1
Pygments==2.11.2
PyJWT==2.3.0
pyparsing==3.0.7
pyrsistent==0.18.1
pysha3==1.0.2
pytest==7.1.1
pytest-cov==3.0.0
pytest-deadfixtures==2.2.1
pytest-django==4.5.2
pytest-randomly==3.11.0
pytest-testmon==1.3.1
pytest-timeout==2.1.0
python-decouple==3.6
python-slugify==6.1.1
python3-openid==3.2.0
pytz==2022.1
PyYAML==6.0
requests==2.27.1
requests-cache==0.9.3
requests-oauthlib==1.3.1
restructuredtext-lint==1.4.0
rlp==2.0.1
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
safety==1.10.3
semantic-version==2.9.0
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
social-auth-app-django==4.0.0
social-auth-core==4.2.0
sortedcontainers==2.4.0
Sphinx==4.5.0
sphinx-autodoc-typehints==1.17.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sqlparse==0.4.2
stack-data==0.2.0
stevedore==3.5.0
StrEnum==0.4.7
structlog==21.5.0
testfixtures==6.18.5
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.10.1
toolz==0.11.2
traitlets==5.1.1
trie==2.0.0a5
types-pytz==2021.3.6
types-PyYAML==6.0.5
typing-extensions==3.10.0.2
uritemplate==4.1.1
url-normalize==1.4.3
urllib3==1.26.9
varint==1.0.2
wcwidth==0.2.5
web3==5.29.0
websockets==9.1
wemake-python-styleguide==0.16.1
yamllint==1.26.3
yarl==1.7.2
zipp==3.7.0
```

### What was wrong?

We have a factory which honestly creates web3 provider and instance:
```
def ensure_web3_py() -> Web3:
    provider = Web3.HTTPProvider(settings.ALCHEMY_HTTP_URI)
    w3 = Web3(provider)
    if not w3.isConnected():
        raise InternalError
    return w3
```

It works perfectly in context of the web-controller which is short-living.
However it produces a problem in a dedicated long-running process that polls a ETH smart contract once in a minute.

On the **first call** right after the process launching all fine, it works. (like in web-controller context)
But after sleeping for the first time, on the **second call** after that isConnected steadily returns `False`.
So the process always exits with the exception on the second run of the real job.

If that's important we're connecting to the Alchemy node, URL is like: "https://eth-goerli.alchemyapi.io/v2/{API_KEY}".

What is the right way to force web3 to reconnect? (can't find in docs, issues and google)

### How can it be fixed?

Currently we fix it on the infrastructure level with `restart: unless-stopped` in the docker-compose.
For sure it's an ugly hack yet doing the trick.

**Comment by fselmo** [comment] 2024-02-26 18:30
I cannot reproduce this at the present time. This is also confusing behavior for an HTTP provider. `is_connected()` makes a request for `web3_clientVersion` under the hood - so as long as your provider returns a response for that request, it should return `True`. If there were any issues in the past I wonder if the API key for Alchemy was being throttled or had any free tier-restrictions on it.

I'm going to close this but if this is still relevant, just ask to re-open with some more provided details / a code snippet.

**Closed by fselmo** 2024-02-26 18:30 UTC
