### ISSUE TITLE
Cannot Call Event 

### ISSUE THREAD

**Issue by mzobe** [ethereum/web3.py#195] opened 2017-07-04 07:54 UTC
* Version: 3.1.8
* Python: 2.7
* OS: MacOS Sierra

Connected successfully with geth 1.5 running on a FreeBSD 11.

from web3 import *

web3 = Web3(KeepAliveRPCProvider())

print web3.eth.accounts //getting the account 

I cannot monitor event changes from the following contract:

pragma solidity ^0.4.0;

contract Title {
    
    address title;
    string _name;
    string _details;
    string _date;
    
    
    event created(string name, address owner);
    event writer(string details, string date);
    
    function Title(string name) {
        
        title = msg.sender;
        _name = name;
        
        created(name,title);
        
    }
    
    function write(string details, string date) public {
        
        _details = details;
        _date = date;
        writer(details,date);
        
    }
    
    function read() constant returns(string, string){
        
        return (_details,_date);
        
        
    }
   
    
}

My attempt is as follows; 

def new_transaction_filter(log_entry):
    print "Event fired"
    print log_entry

new_transaction_filter = web3.eth.filter('latest')
new_transaction_filter.watch(new_transaction_filter)

Results:

The event does not fire while the same is fired in Remix.

Kindly guide.

Thank you.

**Comment by veqtor** [comment] 2017-07-16 12:56
Also having this issue

**Comment by tony71318** [comment] 2017-07-28 06:08
I can't get or watch contract's event.
However, transaction filter works for me though.

How can i fix the code or this is this library's own issue?

`event = myContract.on('event_test')
event.web3.eth.getFilterLogs(event.filter_id)`
or
`event.get()`

These get methods always return empty list.
Need help, thank you.

**Comment by pipermerriam** [comment] 2017-07-28 15:24
What I *think* your running into is errors in the testrpc codebase.  The filtering code and logic in that codebase was written a long time ago and it's not surprising to me if it's the cause.  I'm close to wrapping up a rewrite of that codebase as a new library that should be released within a few weeks which will fix this.  In the meantime, feel free to dive into the testrpc code and see if you can figure out what is causing this.

**Comment by pipermerriam** [comment] 2017-07-28 15:27
btw, I'm sorry this is causing you development troubles.  I am currently stretched very thin across the code-bases that I manage and am having to be very deliberate in where I allocate my time.

**Comment by pipermerriam** [comment] 2017-11-22 17:49
closing this as the filter API has been reworked. Please re-open or re-submit a new issue if you are still having issues.

**Closed by pipermerriam** 2017-11-22 17:49 UTC
