### ISSUE TITLE
Automatically encoding of an arguments for contract method

### ISSUE THREAD

**Issue by alexey-grom** [ethereum/web3.py#748] opened 2018-04-07 07:36 UTC
* Version: 4.0.0
* Python: 3.5
* OS: linux

### What was wrong?

I call a contract method and get this trace:

```
Traceback (most recent call last):
  File "/app/src/views/contract.py", line 69, in call_method
    invoke = method(*arguments.values())
  File "/usr/local/lib/python3.5/site-packages/web3/contract.py", line 903, in __init__
    self._set_function_info()
  File "/usr/local/lib/python3.5/site-packages/web3/contract.py", line 909, in _set_function_info
    self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/web3/utils/contracts.py", line 100, in find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found
```

My problem is that `web3.utils.abi.is_encodable` doesn't consider `int` as representative as bytes array:

```
from web3.utils.contracts import find_matching_fn_abi
from web3.utils.encoding import to_bytes

abi = [
    {'constant': False,
     'inputs': [{'name': '_to', 'type': 'address'},
                {'name': '_value', 'type': 'uint256'},
                {'name': '_fee', 'type': 'uint256'},
                {'name': '_nonce', 'type': 'uint256'},
                {'name': '_v', 'type': 'uint8'},
                {'name': '_r', 'type': 'bytes32'},
                {'name': '_s', 'type': 'bytes32'}],
     'name': 'name',
     'outputs': [{'name': '', 'type': 'bool'}],
     'payable': False,
     'stateMutability': 'nonpayable',
     'type': 'function'},
]

name = 'name'
good_args = (
    '0x3db0a82491cca2b89e61db4c1885a8e745c63265',
    1,
    1,
    1,
    28,
    to_bytes(28959435470761257621766426729547047597677396750272393780686032384044109160873),
    to_bytes(35812761560685972683592328664071490125564303384467730161104237647446031473187),
)
bad_args = (
    '0x3db0a82491cca2b89e61db4c1885a8e745c63265',
    1,
    1,
    1,
    28,
    28959435470761257621766426729547047597677396750272393780686032384044109160873,
    35812761560685972683592328664071490125564303384467730161104237647446031473187,
)

assert find_matching_fn_abi(abi, name, args=good_args, kwargs={})  # pass
assert find_matching_fn_abi(abi, name, args=bad_args, kwargs={})  # raises `ValueError: No matching functions found`
```

Actually it's not problem of web3 I guess but maybe it's possible to improve a validation and encoding there, because after all it raises validation error on contract call:

```
  ....
  File "/usr/local/lib/python3.5/site-packages/web3/utils/normalizers.py", line 121, in abi_address_to_hex
    validate_address(data)
  File "/usr/local/lib/python3.5/site-packages/web3/utils/validation.py", line 116, in validate_address
    raise InvalidAddress("Address has an invalid EIP checksum", value)
web3.exceptions.InvalidAddress: ('Address has an invalid EIP checksum', '0x3db0a82491cca2b89e61db4c1885a8e745c63265')
```

Some kind of validation applies two times and working in different way when try to find method in ABI and when creates a transaction. Isn't?

Maybe could you advise me how to encode automatically a python primitives for any contract method without inspect ABI? I'm sure web3 does it for itself.

**Comment by carver** [comment] 2018-04-09 19:45
> `web3.exceptions.InvalidAddress: ('Address has an invalid EIP checksum', '0x3db0a82491cca2b89e61db4c1885a8e745c63265')`

Try to get the address from a source that checksums the address. If you're interacting with a contract deployed by someone else, request a checksummed address from them, or look it up on Etherscan.

> My problem is that web3.utils.abi.is_encodable doesn't consider int as representative as bytes array.

Unfortunately, you can lose information when converting back and forth from int to bytes. If you have an abi `bytes` value of `b'\x00\x0a'` and convert that to int, you get 10. Convert that back to `bytes` and you get `b'\x0a'`.

You could maybe make the case that it is reasonable to automatically convert `int` to a `bytesN` type with fixed length, since it can be reliably converted to and from `int`. (your example is fixed length) The subtlety of accepting an `int` for some `bytes` types and not others is likely to cause a lot of confusion though. So I'm hesitant to add it.

> Some kind of validation applies two times and working in different way when try to find method in ABI and when creates a transaction. Isn't?

Right, since functions are polymorphic, we have to look up the appropriate contract function at runtime, based on the types of the arguments. The error message can definitely be improved. #757 is tracking that.

> Maybe could you advise me how to encode automatically a python primitives for any contract method without inspect ABI? I'm sure web3 does it for itself.

I don't understand. Surely you need to know what function you're interacting with, and the types of the arguments, which requires looking at the ABI. In general, web3.py *does* convert from native python types to the correct ABI representation.

**Comment by pipermerriam** [comment] 2018-04-09 21:31
> Maybe could you advise me how to encode automatically a python primitives for any contract method without inspect ABI? I'm sure web3 does it for itself.

I think he was asking for this.  You can expand on this if there are additional input types available (I think hex strings are accepted in some places but I can't recall where).

- solidity `int` `uint` -> python `int`
- solidity `string` -> python `str` (expected to be utf8 encoded) or `bytes`
- solidity `bytes` -> python `bytes`
- solidity `bool` -> python `bool`

**Comment by pipermerriam** [comment] 2018-04-09 21:31
closed as this is not a bug, please feel free to continue the conversation.

**Closed by pipermerriam** 2018-04-09 21:31 UTC
