### ISSUE TITLE
The method personal_unlockAccount does not exist

### ISSUE THREAD

**Issue by sjtupingjian** [ethereum/web3.py#727] opened 2018-03-28 12:47 UTC
* Version: 4.0.0
* Python: 3.6
* OS: win

### What was wrong?
When I want to unlock my account by:
``
web3.personal.unlockAccount(valid_from,,'123')
``
It returns error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\com\PycharmProjects\test\venv\lib\site-packages\web3\personal.py", line 43, in unlockAccount
    [account, passphrase, duration],
  File "C:\Users\com\PycharmProjects\test\venv\lib\site-packages\web3\manager.py", line 104, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method personal_unlockAccount does not exist/is not available'}
```
How can I fixed it?

**Comment by boneyard93501** [comment] 2018-03-28 15:53
the error is a pass through from your node, which i presume is geth and i presume you've selected the web3py http provider.  in non-interactive mode, your only options are to either unlock the account at geth startup or over ipc.

**Comment by carver** [comment] 2018-03-28 18:56
Closing as not a bug. Feel free to continue conversation here for assistance, @sjtupingjian

**Closed** 2018-03-28 18:56 UTC

**Comment by MattNguyen** [comment] 2018-04-08 11:41
I ran into this as well. To use IPC, use the following code to access `unlockAccount`:

```python
from web3 import Web3, IPCProvider

web3 = Web3(IPCProvider(ipc_path=IPC_PATH))
web3.unlockAccount(ACCOUNT, PASSWORD)
```
