### ISSUE TITLE
eth_abi.exceptions.InsufficientDataBytes: Tried to read 96 bytes.  Only got 93 bytes when event contains a string

### ISSUE THREAD

**Issue by alex-murashkin** [ethereum/web3.py#928] opened 2018-06-24 01:45 UTC
* Version: 4.2.0
* Python: 3.6.4
* OS: osx

### What was wrong?

When an event with a string attribute of a certain length is attempted to be handled by a web3.py filter, an "eth_abi.exceptions.InsufficientDataBytes" exception is thrown.

* The code which produced the error

A regular web3.py filter for an event MyEvent. The event ABI:
```
...,
{
  anonymous: false,
  inputs: [
    {
      indexed: false,
      name: "id",
      type: "uint256"
    },
    {
      indexed: false,
      name: "actor",
      type: "address"
    },
    {
      indexed: false,
      name: "text1",
      type: "string"
    },
    {
      indexed: false,
      name: "integer1",
      type: "uint256"
    },
    {
      indexed: false,
      name: "integer2",
      type: "uint256"
    }
  ],
  name: "MyEvent",
  type: "event"
},
...
```

* The full output of the error
```
Exception in thread MyEvent thread:
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/username/projects/project-name/main-file.py", line 67, in exec
    for evt in evt_filter.get_new_entries():
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 106, in get_new_entries
    return self._format_log_entries(log_entries)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in _format_log_entries
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in <listcomp>
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 162, in format_entry
    return self.log_entry_formatter(entry)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/events.py", line 189, in get_event_data
    decoded_log_data = decode_abi(log_data_types, log_data)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/abi.py", line 63, in decode_abi
    return decoder(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 135, in decode
    yield HeadTailDecoder.as_decoder(tail_decoder=decoder)(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 116, in decode
    value = cls.tail_decoder(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 162, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 442, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 96 bytes.  Only got 93 bytes

```

Please find the Etherscan anonymized event attached: ![image 1](https://user-images.githubusercontent.com/1721409/41815105-a44a4a8c-772e-11e8-8274-cd651d5358b8.png)

It does sounds like this error happens when processing a string attribute, because:
1. In the test that lead to an error, the length of the "text1" attribute was 93
2. When a test was repeated with "text1" of the length 96, there was no issue: the event was handled as expected.

* What type of node you were connecting to.
Geth/v1.8.6-stable-12683fec/linux-amd64/go1.10

### How can it be fixed?

No concrete suggestions, but looks like there may be an issue with calculation of expected length of a string attribute in certain cases?

**Comment by carver** [comment] 2018-06-26 00:47
Can you provide an example that's not redacted that allows us to reproduce the problem?

**Comment by alex-murashkin** [comment] 2018-06-26 14:58
Sure. I'll come up with a minimal example and share it as soon as I have it.

**Comment by alex-murashkin** [comment] 2018-06-30 00:18
Hi,

Please find an example attached:
```
pragma solidity 0.4.23;

contract TestContract {
  event SomeEvent(
    uint256 requestId,
    address requestor,
    string uri,
    uint256 price,
    uint256 requestTimestamp
  );

  function EmitSomeEvent(string uri, uint256 price) external returns(uint256) {
    uint256 requestId = 123;
    emit SomeEvent(requestId, msg.sender, uri, price, block.timestamp); // solhint-disable-line not-rely-on-time
    return requestId;
  }
}
```
ABI:
```
[
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "requestId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "requestor",
        "type": "address"
      },
      {
        "indexed": false,
        "name": "uri",
        "type": "string"
      },
      {
        "indexed": false,
        "name": "price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "requestTimestamp",
        "type": "uint256"
      }
    ],
    "name": "SomeEvent",
    "type": "event"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "uri",
        "type": "string"
      },
      {
        "name": "price",
        "type": "uint256"
      }
    ],
    "name": "EmitSomeEvent",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
```

When calling `EmitSomeEvent("abc", 10000000000000000000)`, and the event is being processed by the filter, the following exception:

```
Exception in thread SomeEvent thread:
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/username/projects/mytest/test/test.py", line 76, in exec
    for evt in evt_filter.get_new_entries():
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 106, in get_new_entries
    return self._format_log_entries(log_entries)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in _format_log_entries
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in <listcomp>
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/filters.py", line 162, in format_entry
    return self.log_entry_formatter(entry)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/web3/utils/events.py", line 189, in get_event_data
    decoded_log_data = decode_abi(log_data_types, log_data)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/abi.py", line 63, in decode_abi
    return decoder(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 135, in decode
    yield HeadTailDecoder.as_decoder(tail_decoder=decoder)(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 116, in decode
    value = cls.tail_decoder(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 162, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/Users/username/.pyenv/versions/3.6.4/lib/python3.6/site-packages/eth_abi/decoding.py", line 442, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 3 bytes
```

**Comment by carver** [comment] 2018-06-30 00:39
Ah yes, there is a bug in Solidity, where functions marked `external` create events that have incorrect log encodings. Check out: https://github.com/ethereum/solidity/issues/3493

The only solutions I know of are:
- Drop the `external` modifier
- wait for Solidity 0.5.0 to come out.

---

Closing because this isn't a Web3.py bug, but feel free to continue the conversation here.

**Closed by carver** 2018-06-30 00:39 UTC

**Comment by alex-murashkin** [comment] 2018-06-30 12:36
Thanks @carver , this was helpful!
