### ISSUE TITLE
EventFilter doesn't work on ConciseContract contracts

### ISSUE THREAD

**Issue by misteraverin** [ethereum/web3.py#465] opened 2017-11-23 09:11 UTC
* Version: 3.16.3
* Python: 3.6.3
* OS: osx

### What was wrong?

I have already created contract and deployed to ethereum mainnet. Now I wanna read logs. But I can't as calling `print(contract_instance.address)` and `contract_instance.eventFilter('Transfers')` show me error log. What am I doing wrong? @carver @pipermerriam 

Code, which produces error:

```
import web3

from web3 import Web3, KeepAliveRPCProvider, IPCProvider
from web3.contract import ConciseContract
from solc import compile_source


ADDRESS = "..."
START_BLOCK = 4551217
END_BLOCK = 4599662

contract_source_code = '''...
'''


compiled_sol = compile_source(contract_source_code) # Compiled source code
contract_interface = compiled_sol['<stdin>:CustomToken']


web3 = Web3(KeepAliveRPCProvider(host='...', port='8545'))

contract_instance = web3.eth.contract(contract_interface['abi'], ADDRESS, ContractFactoryClass=ConciseContract)

transfer_filter = contract_instance.eventFilter('Transfers')
```

Errot output:
```
Traceback (most recent call last):
  File "analysis.py", line 488, in <module>
    transfer_filter = contract_instance.eventFilter('InvestmentInBTC')
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 805, in __call__
    return self.__prepared_function(**kwargs)(*args)
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 834, in call_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.6/site-packages/web3/utils/decorators.py", line 17, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 695, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 734, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 663, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/web3/contract.py", line 627, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found
```

I was connecting to infura mainnet node.

**Comment by FireZi** [comment] 2017-11-25 15:54
Try this
`
contract = web3.eth.contract(contract_interface['abi'], ADDRESS)

transfer_filter = contract.eventFilter('Transfers')
`
(without _ContractFactoryClass_ for `.eventFilter`)

**Comment by carver** [comment] 2017-11-29 01:05
Looks like a duplicate of: https://ethereum.stackexchange.com/questions/31428/cant-access-to-contract-functions-via-web3-py

@FireZi note that for more forward compatibility, you should use `contract(ADDRESS, abi=contract_interface['abi'])`. ABI will no longer be accepted as a positional argument in v4.

**Closed by carver** 2017-11-29 01:05 UTC
