### ISSUE TITLE
Something wrong with getBlock

### ISSUE THREAD

**Issue by lipangit** [ethereum/web3.py#973] opened 2018-07-28 16:27 UTC
* Version: 4.4.1
* Python: 3.7.0
* OS: osx

When I connect my local geth --rpc

![image](https://user-images.githubusercontent.com/2038071/43358493-745e8664-92c5-11e8-9d55-038bf25c308a.png)

and I get the result

![image](https://user-images.githubusercontent.com/2038071/43358498-82614aa8-92c5-11e8-8e0c-339da2585f63.png)

But I use web3.js to connect the same rpc in my local server

![image](https://user-images.githubusercontent.com/2038071/43358523-f0a2b0b0-92c5-11e8-8884-79e714d03e1b.png)

I get the result 

![image](https://user-images.githubusercontent.com/2038071/43358529-0d68de5e-92c6-11e8-9bac-d101ab83066d.png)

I thing web3.py is wrong What can I do ?

**Comment by lipangit** [comment] 2018-07-28 16:46
and web3.eth.getBalance(address)  every address's ballance are 0

**Comment by voith** [comment] 2018-07-29 06:35
is your node synced? what `web3.eth.syncing` say?

**Comment by lipangit** [comment] 2018-07-29 08:57
AttributeDict({'currentBlock': 6050271, 'highestBlock': 6050347, 'knownStates': 0, 'pulledStates': 0, 'startingBlock': 6050271})

**Comment by lipangit** [comment] 2018-07-29 09:22
run the scrpt again 20min later,  I got the same result

**Comment by lipangit** [comment] 2018-07-29 15:55
but why eth.getBanlance()  every address is = 0

**Comment by lipangit** [comment] 2018-07-29 15:55
What can I do next

**Comment by voith** [comment] 2018-07-29 16:08
> but why eth.getBanlance() every address is = 0

Balance is something that is queried from the state trie. Till your state trie gets synced your balance will be shown as zero! read [this](https://github.com/ethereum/go-ethereum/issues/16251#issuecomment-371449572).

**Comment by lipangit** [comment] 2018-07-29 16:13
@voith I will collect that issue and learn It carefully

**Comment by lipangit** [comment] 2018-07-29 16:13
Thank you

**Comment by carver** [comment] 2018-07-30 19:08
Closing because it's not a bug, but feel free to continue to comment for support.

**Closed by carver** 2018-07-30 19:08 UTC
