### ISSUE TITLE
Cannot send the double list into a function with parameter type bytes32[10][] 

### ISSUE THREAD

**Issue by ayeteng** [ethereum/web3.py#1127] opened 2018-10-26 02:40 UTC
* Version: 4.7.2
* Python: 3.6
* OS: osx
* `pip freeze` output

```
urllib3==1.23
Pillow==5.2.0
py_solc==2.2.0
web3==4.7.2
requests==2.19.1
ethereum_input_decoder==0.2.2
tornado==5.1
bcrypt==3.1.4
ipfsapi==0.4.3
mysqlclient==1.3.13
PyJWT==1.6.4
pymongo==3.7.1
python-telegram-bot==11.1.0
pytz==2018.5
```

### What was wrong?

The solidity function defined:
```
function set_first_step(bytes32[10][] INPUT_1) public {...}
```

When use web3 tx to call solidity function, I try to use double list but I get complain from the output. How can I fix this issue?

The INPUT_1 array:
```
INPUT_1 = [[bytes(range(idx, 32 + idx)) for idx in range(10)] * 2]
```

The web3 function:
```
tx_hash = self.contract_instance['../contracts/n1.sol:node1'].functions.set_first_step(INPUT1).transact({'from': self.w3.toChecksumAddress(unit['detail_list'][1]), 'gas': 3400000})
```

The output from web3:
```
Could not identify the intended function with name `set_first_step`, positional argument(s) of type `( <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `set_first_step`: ['set_first_step(bytes32[10][])']
Function invocation failed due to no matching argument types.
```

**Comment by pipermerriam** [comment] 2018-11-13 18:29
Submitted to gitcoin for bounty.  If any "bounty hunters" come along.  The definition of done for this will be:

- New tests to ensure that our `is_encodable` function correctly handles this.
- Fix for the actual bug which *may* be something that needs to be done in the [`eth-abi`](https://github.com/ethereum/eth-abi) library.

**Comment by pipermerriam** [comment] 2018-11-13 18:29
cc @davesque as `eth-abi` is your domain just so this is on your radar.

**Comment by carver** [comment] 2018-11-14 23:39
It's subtle, but the example input data is not the correct type:

```py
# this is what you have:
assert [[3, 4] * 2] == [[3, 4, 3, 4]]

# this is what you want:
assert [[3, 4]] * 2 == [[3, 4], [3, 4]]
```

Closing as not a bug. Noted in #1117 for future work to help people figure out their issue earlier.

**Closed by carver** 2018-11-14 23:39 UTC
Labels: Bug

**Comment by carver** [comment] 2018-11-14 23:42
(_note that this version passes_)

```py
from web3._utils.abi import is_encodable

typ = 'bytes32[10][]'
val =  [[bytes(range(idx, 32 + idx)) for idx in range(10)]] * 2

assert is_encodable(typ, val)
```
:tada:
