### ISSUE TITLE
Event().createFilter() address argument_filters problem

### ISSUE THREAD

**Issue by MatthiasLohr** [ethereum/web3.py#1439] opened 2019-08-28 07:40 UTC
* Version: 5.0.2
* Python: 3.7
* OS: linux
* `pip freeze` output

```
attrdict==2.0.1
base58==1.0.3
certifi==2019.6.16
chardet==3.0.4
cytoolz==0.10.0
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-tester==0.2.0b2
eth-typing==2.1.0
eth-utils==1.6.4
hexbytes==0.2.0
idna==2.8
ipfshttpclient==0.4.12
jsonschema==2.6.0
lru-dict==1.1.6
lxml==4.4.0
multiaddr==0.0.8
netaddr==0.7.19
parsimonious==0.8.1
pkg-resources==0.0.0
protobuf==3.9.1
py-solc-x==0.5.0
pycryptodome==3.8.2
requests==2.22.0
rlp==1.1.0
semantic-version==2.6.0
six==1.12.0
toolz==0.10.0
urllib3==1.25.3
varint==1.0.2
web3==5.0.2
websockets==7.0
```

### What was wrong?

Filtering for address seems not to be working:

```python
event_filter = self._contract_wrapper.events.MoneyDepositEvent().createFilter(
    fromBlock=0,
    toBlock='latest',
    argument_filters={
        'seller': Web3.toChecksumAddress(recipient)
    }
)
```

blocks forevery. But

```python
event_filter = self._contract_wrapper.events.MoneyDepositEvent().createFilter(
    fromBlock=0,
    toBlock='latest',
    argument_filters={
    }
)
print(event_filter.get_new_entries())
```

gives `AttributeDict({'seller': '0xE3288441D0A41D3A6b99A250E3B43bA87c7601cD', ...`

Am I doing something wrong? How to submit addresses for the filter (lower/upper/checksum)?

**Comment by MatthiasLohr** [comment] 2019-08-28 09:08
Found one solution: It works, if the lowercase address is used:
```python
Web3.toChecksumAddress(recipient).lower()
```

Is that the intended behavior? Can it please included in the docs?

**Comment by kclowes** [comment] 2019-09-05 20:23
Sorry, I lost track of this @MatthiasLohr. I don't think that's intended behavior, but I'll look into it soon.

**Comment by MatthiasLohr** [comment] 2019-09-08 17:08
That would be great, thanks.

**Comment by pipermerriam** [comment] 2019-10-03 16:45
@MatthiasLohr what backend are you using?  geth node?  ganache?  I believe there was a bug in ganache for a while that didn't properly normalize checksummed addresses.

**Comment by MatthiasLohr** [comment] 2019-10-03 17:07
I used the infura services, but no idea which client hey have.

**Comment by pipermerriam** [comment] 2019-10-03 17:12
Seems whatever nodes they are using, they are not properly normalizing checksummed addresses.  I'm closing this as it isn't a web3.py bug.  Seems like lowercasing the address was a suitable workaround.

**Closed by pipermerriam** 2019-10-03 17:12 UTC
