### ISSUE TITLE
Empty event log 

### ISSUE THREAD

**Issue by jfdelgad** [ethereum/web3.py#730] opened 2018-03-31 13:14 UTC
* Version: 4.b13
* Python: 3.6
* OS: win
* Geth 
* Rinkeby

I have a simple contract that produces events. The events are registered on mist correctly.
I can interact with the contract without problems but can't get the events. I am simply doing this:

"RegisterCall" is the name of the event in the contract.

```
event_filter = mycontract.events.RegisterCall.createFilter(fromBlock=1)
event_filter.get_all_entries()
>>>[]
```

Any suggestion will be appreciated.

**Comment by EralpB** [comment] 2018-04-01 14:34
Can you please put all your code? after instantiating the contract object you need to force update it's address to lowercase address (no EIP-55).

**Comment by jfdelgad** [comment] 2018-04-01 18:18
Hi, thanks for your answer

I am not forcing the address to lower case, I will try and will post the results. In the mean time this is the code. I remove the contract_soruce_code because is long.
 
compiled_sol = compile_source(contract_source_code) 
mycontract.Interface = compiled_sol['<stdin>:MyContract']

```
mycontractAddress = '0x36e87aBE249D4146fA2FED32Ce13f592122c611E'
mycontract = w3.eth.contract(address=mycontractAddress, abi=mycontractInterface['abi'],ContractFactoryClass=ConciseContract)
w3.personal.unlockAccount(w3.eth.accounts[0], '*********', duration=None)

event_filter = mycontract.events.RegisterCall.createFilter(fromBlock=1)
while True:
    print(event_filter.get_all_entries())
    time.sleep(2)

```

**Comment by dylanjw** [comment] 2018-04-02 04:39
Can you try the old api, so I can see if this is a problem specific to the new api.

```python
event_filter = mycontract.eventFilter('RegisterCall', filter_params={'fromBlock': 1})
```

Are you able to see results with a simple block filter?

```python
block_filter = w3.eth.filter("latest")
```

If you could post more of your code, it would be helpful.

**Comment by EralpB** [comment] 2018-04-02 08:25
@jfdelgad please try this one:

```
mycontractAddress = '0x36e87aBE249D4146fA2FED32Ce13f592122c611E'
mycontract = w3.eth.contract(address=mycontractAddress, abi=mycontractInterface['abi'],ContractFactoryClass=ConciseContract)
mycontract.address = '0x36e87abe249d4146fa2fed32ce13f592122c611e'  # THIS LINE!
w3.personal.unlockAccount(w3.eth.accounts[0], '*********', duration=None)

# I'm not sure if the following change is required, but just to be on the safe side:
event_filter = mycontract.eventFilter('RegisterCall', {'fromBlock': 0,'toBlock': 'latest'})
while True:
    print(event_filter.get_all_entries())
    time.sleep(2)

```

**Comment by jfdelgad** [comment] 2018-04-02 16:13
Hi Guys

putting the address in lower case throw an error because the address is validated when the event filter is created.

However, by looking at Eralp answer I realize that I never initialize the address in mycontract as he pointed out. That was the issue.

Thanks a lot

**Comment by jfdelgad** [comment] 2018-04-02 21:28
Hi

I have again an issue:

This works as I commeneted above (give me a warnig about being deprecated), but works fine
```
myfilter = mycontract.eventFilter('RegisterCall', {'fromBlock': 0,'toBlock': 'latest'});
eventlist = myfilter.get_all_entries()

```
I am requested to do use the new api but doesnt work: The list of events is empty
```
myfilter =  myfilter.events.RegisterCall.createFilter(fromBlock=1,toBlock='latest')
eventlist = myfilter.get_all_entries()

```

Any ideas what is going on?

**Comment by carver** [comment] 2018-04-02 23:46
Is the event in block 0? Your second example skipped it. Try this:

```py
myfilter =  myfilter.events.RegisterCall.createFilter(fromBlock=0, toBlock='latest')
eventlist = myfilter.get_all_entries()
```

**Comment by kfichter** [comment] 2018-04-03 22:27
@carver Unfortunately because `createFilter` does an `if not fromBlock` check, `fromBlock` cannot be 0 (because 0 is falsy)

**Comment by kfichter** [comment] 2018-04-03 22:45
I'm having a similar problem getting events to work at all.

I have a testing method in my contract:
```
    function testDepositEvent()
        public
    {
        Deposit(msg.sender, 1);
    }
```

I then call that method via web3.py:
```
    event_filter = root_chain.events.Deposit.createFilter(fromBlock='latest')
    root_chain.functions.testDepositEvent().transact({
        'from': ACCOUNT1
    })
    ...
    print(event_filter.get_all_entries()) # []
```

**Comment by carver** [comment] 2018-04-04 18:26
Can you confirm that the transaction has been mined, like:

```py
    event_filter = root_chain.events.Deposit.createFilter(fromBlock='latest')
    txn_hash = root_chain.functions.testDepositEvent().transact({
        'from': ACCOUNT1
    })
    ...
    w3.eth.getTransactionReceipt(txn_hash)
    print(event_filter.get_all_entries()) # []
```

**Comment by kfichter** [comment] 2018-04-04 19:12
@carver It does seem to be mined. Here's the prettified transaction receipt:

```
{
   'contractAddress':None,
   'cumulativeGasUsed':23401,
   'status':1,
   'blockNumber':20,
   'blockHash':HexBytes('0x2c40d0fa4b9953e33674518d992b64e464e536a9a2b351cd167952fd0d634cc0'),
   'transactionIndex':0,
   'transactionHash':HexBytes('0xd95163c4f91764838d6f3401f319eb37d6d336df3f7485fc74b7d64a2c019be2'),
   'logs':[
      AttributeDict({
         'address':'0x607C0e51D90D118612036d22036c0438c41fD8A1',
         'blockNumber':20,
         'logIndex':0,
         'transactionIndex':0,
         'transactionHash':HexBytes('0xd95163c4f91764838d6f3401f319eb37d6d336df3f7485fc74b7d64a2c019be2'),
         'topics':[
            HexBytes('0x90890809c654f11d6e72a28fa60149770a0d11ec6c92319d6ceb2bb0a4ea1a15'),
            HexBytes('0x0000000000000000000000004b3ec6c9dc67079e82152d6d55d8dd96a8e6aa26'),
            HexBytes('0x0000000000000000000000000000000000000000000000000000000000000064')
         ],
         'type':'mined',
         'blockHash':HexBytes('0x2c40d0fa4b9953e33674518d992b64e464e536a9a2b351cd167952fd0d634cc0'),
         'data':'0x0000000000000000000000000000000000000000000000000000000000000000'
      })
   ],
   'gasUsed':23401
}
```

And `event_filter.get_all_entries()` still returns `[]`

I'm running ganache-cli v6.1.0

**Comment by jfdelgad** [comment] 2018-04-04 20:33
I still have the problem and I am using plain python with Geth. As I mentioned the old method for the filtering works, the new one doesn't.

**Comment by dylanjw** [comment] 2018-04-06 03:07
@jfdelgad Have you re-tried with the latest web3 (installed from the master branch) that includes #742, and setting the block number to 0?

If you are still having an issue after following these two steps, can you post a complete example demonstrating the error you are having.

An complete example including contract code, any event emitting transactions, and the filter creation and filter polling.  Something like:

```pythonimport time
import web3

from solc import compile_source

from web3 import Web3, EthereumTesterProvider


contract_code = '''
contract EmitEvent {

    uint8 public _myVar;
    event Event(string indexed _var);

    function emitEvent() public {
        Event("!!!");
    }
}
'''

def wait_on_tx_receipt(tx_hash):
    start_time = time.time()
    while True:
        if start_time + 60 < time.time():
            raise TimeoutError("Timeout occurred waiting for tx receipt")
        if w3.eth.getTransactionReceipt(tx_hash):
            return w3.eth.getTransactionReceipt(tx_hash)

compiled_sol = compile_source(contract_code)
contract_interface = compiled_sol['<stdin>:EmitEvent']

w3 = Web3(EthereumTesterProvider())

contract = w3.eth.contract(
    abi=contract_interface['abi'],
    bytecode=contract_interface['bin'])


tx_hash = contract.constructor().transact(
    transaction={
        'from': w3.eth.accounts[0],
        'gas': 410000})

tx_receipt = w3.eth.getTransactionReceipt(tx_hash)
contract_address = tx_receipt['contractAddress']

# Instatiate contract
emitEvent = w3.eth.contract(address=contract_address, abi=contract_interface['abi'])

# Create log filter instance
_filter = emitEvent.events.Event.createFilter(fromBlock=0)

# Event emitting transaction
tx_hash = emitEvent.functions.emitEvent().transact()

# Wait for transaction to be mined
receipt = wait_on_tx_receipt(tx_hash)

# Poll filter
print(_filter.get_new_entries())
```

```sh
$ python emit_event_example.py
[AttributeDict({'args': AttributeDict({'_var': b"\x91xd\xb8)_k~\x97\x0f4\xc7\xdf'\xaa\xf2\\\xbf\x1d\xc3\xb9\x12\xe9omK\xbd\n\x99\xbeF\xb3"}), 'event': 'Event', 'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xa2065811d730e217de416fb20ef1a4a9f48ab64d57cd0dc80f37020bf9489ec2'), 'address': '0xF2E246BB76DF876Cef8b38ae84130F4F55De395b', 'blockHash': HexBytes('0xbf64c2de41f858cc697c165ae6adb07a54b85cd73134f7e4f097ce5f28f97644'), 'blockNumber': 2})]
```

**Comment by ti6oti6o** [comment] 2018-04-06 03:44
exact same problem as  jfdelgad: I am using python (web3py(4.0.0)...Code I use is:
```
contract_address = w3.toChecksumAddress("0xc778417E063141139Fce010982780140Aa0cD5Ab")
contract_instance = w3.eth.contract(address=contract_address, abi=contract_abi)
myfilter_new=contract_instance.events.Deposit.createFilter(fromBlock=2058615, toBlock='latest')
myfilter_old=contract_instance.eventFilter('Deposit',{'fromBlock':2058615,'toBlock':'latest'})
print("     filterDeposit (OLD METHOD)--",myfilter_old.get_all_entries())
print("     filterDeposit (NEW METHOD)--",myfilter_new.get_all_entries())
```

**Comment by dylanjw** [comment] 2018-04-06 04:45
Here is a self contained test, borrowing the contract code from the rinkeby address: "0xc778417E063141139Fce010982780140Aa0cD5Ab"
https://gist.github.com/dylanjw/cac15da222b933616e1a6cd0ad5515af

Im getting an exception because the topic is incorrect for the event signature:

```
Traceback (most recent call last):
  File "./create_event_example.py", line 800, in <module>
    _filter = WETH9.events.Deposit.createFilter(fromBlock=0)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/utils/decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/contract.py", line 1190, in createFilter
    log_filter = self.web3.eth.filter(event_filter_params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/eth.py", line 312, in filter
    [filter_params],
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/validation.py", line 46, in middleware
    return make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/providers/eth_tester/middleware.py", line 317, in middleware
    return make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/fixture.py", line 12, in middleware
    return make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/providers/eth_tester/main.py", line 46, in make_request
    response = delegator(self.ethereum_tester, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/providers/eth_tester/defaults.py", line 111, in create_log_filter
    filter_id = eth_tester.create_log_filter(**filter_params)
  File "/home/dwilson/Develop/Eth/contract_testing/venv36/lib/python3.6/site-packages/eth_tester/main.py", line 551, in create_log_filter
    topics=topics,
  File "/home/dwilson/Develop/Eth/contract_testing/venv36/lib/python3.6/site-packages/eth_tester/validation/inbound.py", line 140, in validate_filter_params
    raise ValidationError(invalid_topics_message)
eth_tester.exceptions.ValidationError: Topics must be one of `None`, an array of 32 byte hexidecimal encoded strings, or an array of arrays of 32 byte hexidecimal strings
```
```
> /home/dwilson/Develop/Projects/ethereum/web3.py/web3/contract.py(1191)createFilter()
-> log_filter = self.web3.eth.filter(event_filter_params)
(Pdb) event_filter_params
{'topics': [{}, ['0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c']], 'address': ['0xF2E246BB76DF876Cef8b38ae84130F4F55De395b', '0xF2E246BB76DF876Cef8b38ae84130F4F55De395b'], 'fromBlock': 0, 'toBlock': 'latest'}
```

**Comment by SteelStrider** [comment] 2018-04-11 11:33
Same problem. (v. 4.1.0)
Only in my case does not work neither the old version nor the new one...

        filter_new = Contracts.eth_pandora_con.events.TestEvent.createFilter(fromBlock=0)
        filter_old = Contracts.eth_pandora_con.eventFilter('TestEvent')

        new = filter_new.get_all_entries() -> []
        old = filter_old.get_all_entries() -> []
   
       create_tx_hash_1 = Contracts.eth_pandora_con.functions.testMethod().transact(
            {'from': '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef'})
        #Hash received and verified         

        new = filter_new.get_all_entries() -> []
        old = filter_old.get_all_entries() -> []

Most likely I'll be back temporarily to version 3.16.5

**Comment by carver** [comment] 2018-04-11 16:56
@SteelStrider are you using ganache?

**Comment by SteelStrider** [comment] 2018-04-12 07:13
Hi Carver !
I re read the entire branch again for this error. 
Yes. initial tests were conducted on ganache and different versions of the library (3.16.5 and 4.1.0) was used. 
3.16.5 - works great
4.1.0   - looks like it works on rinkeby testnet but does not work with gnache 

filter_new = Contracts.eth_contract.events.TestEvent.createFilter(fromBlock=0)
new = filter_new.get_all_entries() -> returned a previous method call log record (what is great)

At the same time today conducted a test for rinkeby and ran into another error on transact method
create_tx_hash_1 = Contracts.eth_contract.functions.TestRequest().transact({'from': 'my_test_address'})

    raise type(exc)("Could not format value %r as field %r" % (item, key)) from exc
ValueError: Could not format value '0xd683010804846765746886676f312e3130856c696e757800000000000000000062d962fb994e8e3b8a5ed527a36cf8bde9af02f904fcfc7a5ec77c525103b6e238f0a9e7fef32597c063d8f2ee29d28481eac08de4557330b8098fb8017484db00' as field 'extraData'

And since this test method launches test event I can not say with 100% certainty that under the rinkbi all works just fine...
Nevertheless, this issue is important for me ) 
If I have any news on this subject, I will inform

**Comment by carver** [comment] 2018-04-12 17:37
> 4.1.0 - looks like it works on rinkeby testnet but does not work with gnache

Yes, I have confirmed that ganache filters are case-sensitive for the address of the contract, which is a bug in ganache. See https://github.com/trufflesuite/ganache-core/issues/97

Can you consider using eth-tester instead of ganache? http://web3py.readthedocs.io/en/stable/providers.html#ethereumtesterprovider

> At the same time today conducted a test for rinkeby and ran into another error on transact method

We're working on a better error message for that extraData message in #756 -- it would say something like: check out how to add a middleware to use geth-style proof-of-authority: http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority

**Comment by ti6oti6o** [comment] 2018-04-17 03:36
dylanjw: Could the 'Topics' issue you get be coming from the fact that you are using EthereumTesterProvider (I use HTTPProvider)? ... I still get the same issue: he new methodology (createFilter) does not return any results (and EventFilter does)...Does anyone have a workaround?

**Comment by dylanjw** [comment] 2018-04-17 15:32
@ti6oti6o Have you tried using 4.1?  The generation of the topic filters is independent of the provider, so the issue would occur with both.

Can you paste the output of your filter's `filter_params` attribute?  

for example:

```python
>>> _filter = WETH9.events.Deposit.createFilter(fromBlock=0)
>>> _filter.filter_params
{'topics': ['0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c'], 'address': ['0xF2E246BB76DF876Cef8b38ae84130F4F55De395b', '0xF2E246BB76DF876Cef8b38ae84130F4F55De395b'], 'fromBlock': 0, 'toBlock': 'latest'}
```

**Comment by ti6oti6o** [comment] 2018-04-18 03:32
Here is the filter_params output using the new method:
`{'topics': [[], ['0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c']], 'address': ['0xc778417E063141139Fce010982780140Aa0cD5Ab', '0xc778417E063141139Fce010982780140Aa0cD5Ab'], 'fromBlock': 2110000, 'toBlock': 'latest'}`

Here is the filter_params output using the old method:
`{'topics': ['0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c'], 'address': '0xc778417E063141139Fce010982780140Aa0cD5Ab', 'fromBlock': 2110000, 'toBlock': 'latest'}`

I haven't tried 4.1 but dont want to as it is unstable and I need a stable version for what I am doing...

**Comment by ti6oti6o** [comment] 2018-04-18 03:33
To clarify:
old method: 
`myfilter_old=contract_instance.eventFilter('Deposit',{'fromBlock':2110000,'toBlock':'latest'})`
new method: 
`myfilter_new=contract_instance.events.Deposit.createFilter(fromBlock=2110000, toBlock='latest')`

**Comment by carver** [comment] 2018-04-18 23:59
> I haven't tried 4.1 but dont want to as it is unstable

Why do you say it's unstable?

**Comment by carver** [comment] 2018-04-25 16:16
ganache has a known bug. Closing as a duplicate of #674

**Closed by carver** 2018-04-25 16:16 UTC

**Comment by jfdelgad** [comment] 2018-05-19 20:44
Guys, thus still don't work. The all method works though.

**Comment by carver** [comment] 2018-05-21 19:12
@jfdelgad what web3py version are you on?

**Comment by jfdelgad** [comment] 2018-05-22 09:27
Updated to the last version and got it working! Thanks.

**Comment by DogLi** [comment] 2018-06-15 10:00
same problem with:

* Version: 4.3.0
* Python: 3.6
* OS: OSX
* Geth
* RoPsten

contract is:

```js
    function () payable {
        emit Log(msg.sender, players.length);
    }
    event Log(address indexed _addr, uint indexed _index);
```

python code:

```python
    def watch(self):
        log_filter = self.contract.events.Log.createFilter(fromBlock=0)
        #log_filter = self.contract.eventFilter('Log', {'fromBlock': 0})
        while True:
            log_events = log_filter.get_all_entries()
            if not log_events:
                time.sleep(3)
                print("no log found")
                continue
            for event in log_events:
                self.process_log_event(event)
            time.sleep(1)
```

When someone sends ether to the contract address, I can not get the log!

**Comment by linerking** [comment] 2019-12-21 16:31
I have the same problem, the filter created by the createFilter method returns an empty array, but the old version of eventFilter is no longer supported by the web3.py.
```
Traceback (most recent call last):
  File "dapp.py", line 42, in <module>
    modify_filter = contracts["modifier"].eventFilter("modified_student",{'fromBlock': "latest"})
AttributeError: 'Contract' object has no attribute 'eventFilter'
```  
by the way, the simplest filter to select the latest block works well 
anybody can help?

**Comment by carver** [comment] 2020-01-06 19:56
> I have the same problem, the filter created by the createFilter method returns an empty array, but the old version of eventFilter is no longer supported by the web3.py.
> 
> ```
> Traceback (most recent call last):
>   File "dapp.py", line 42, in <module>
>     modify_filter = contracts["modifier"].eventFilter("modified_student",{'fromBlock': "latest"})
> AttributeError: 'Contract' object has no attribute 'eventFilter'
> ```
> 
> by the way, the simplest filter to select the latest block works well
> anybody can help?

---

A good place to ask for help is https://ethereum.stackexchange.com/questions/tagged/web3.py -- or if no response there, then https://gitter.im/ethereum/web3.py
