### ISSUE TITLE
TypeError raised in wait_for_transaction_receipt when Timeout occurs and transaction_hash is a string

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [ethereum/web3.py#2061] opened 2021-07-03 08:58 UTC
Hi,
I noticed that when I pass a string to `wait_for_transaction_receipt` and a Timeout occurs then a new TypeError is raised from the following line:
https://github.com/ethereum/web3.py/blob/f13d78a6388fb4727f7ee7d11d4bd12674c67dc2/web3/eth.py#L536

The TypeError is "Unsupported type: The primitive argument must be one of: bytes,bytearray, int or bool and not str" and is due to `to_hex` not handling a hex string as its first argument.
The issue is that the `transaction_hash` argument of `wait_for_transaction_receipt` is declared as `_Hash32`, which can be a `HexStr`, so the error handling part of the function should also assume it can be.

**Comment by kclowes** [comment] 2021-07-07 16:54
Thanks for the report @Celeborn2BeAlive! This is a duplicate of #2043 - closing since it's already tracked there.

**Closed by kclowes** 2021-07-07 16:54 UTC
