### ISSUE TITLE
Troubles with AsyncWeb3

### ISSUE THREAD

**Issue by 4vadim4** [ethereum/web3.py#3549] opened 2024-12-03 13:16 UTC
i use Python 3.12.0, web3 7.6.0 and Testnet (Sepolia) Infura
but i can't repeat the result described in the [documentation](https://web3py.readthedocs.io/en/stable/quickstart.html#remote-providers), for AsyncWeb3 i always get "false" status or errors for that case:

```
>>> import asyncio
>>> from web3 import Web3, AsyncWeb3
>>>
>>> WEB3_HTTP_URI = 'https://sepolia.infura.io/v3/<MY-API-KEY>'
>>>
>>> w3 = Web3(Web3.HTTPProvider(WEB3_HTTP_URI))
>>> w3.is_connected()  
True
```

but:
```
>>> w3_async = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(WEB3_HTTP_URI))
>>> await w3_async.is_connected()
False
```

or:
```
>>> import asyncio
>>> from web3 import AsyncWeb3
>>> 
>>> WEB3_HTTP_URI = 'https://sepolia.infura.io/v3/<MY-API-KEY>'
>>> 
>>> w3 = AsyncWeb3(AsyncWeb3.AsyncHTTPProvider(WEB3_HTTP_URI))
>>> 
>>> w3.eth.get_block('latest')
<coroutine object AsyncEth.get_block at 0x10e63d9a0>
>>> await w3.eth.get_block('latest')
Traceback (most recent call last):
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1116, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1126, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1159, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/eth/async_eth.py", line 427, in get_block
    return await self._get_block(block_identifier, full_transactions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/module.py", line 159, in caller
    result = await async_w3.manager.coro_request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/manager.py", line 415, in coro_request
    response = await self._coro_make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/manager.py", line 342, in _coro_make_request
    return await request_func(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/middleware/base.py", line 96, in middleware
    await make_request(method, params),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/middleware/base.py", line 96, in middleware
    await make_request(method, params),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/middleware/base.py", line 96, in middleware
    await make_request(method, params),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/_utils/caching/caching_utils.py", line 365, in wrapper
    return await func(provider, method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/providers/rpc/async_rpc.py", line 161, in make_request
    raw_response = await self._make_request(method, request_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/providers/rpc/async_rpc.py", line 138, in _make_request
    return await self._request_session_manager.async_make_post_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/_utils/http_session_manager.py", line 284, in async_make_post_request
    response = await self.async_get_response_from_post_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/_utils/http_session_manager.py", line 278, in async_get_response_from_post_request
    response = await session.post(endpoint_uri, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1118, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host sepolia.infura.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
>>> 
```

or:
```
>>> import asyncio
>>> from web3 import AsyncWeb3
>>>
>>> WEB3_WS_URI = 'wss://sepolia.infura.io/ws/v3/<MY-API-KEY>'
>>>
>>> w3_ws_async = await AsyncWeb3(AsyncWeb3.WebSocketProvider(WEB3_WS_URI))
Traceback (most recent call last):
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/providers/persistent/persistent.py", line 101, in connect
    await self._provider_specific_connect()
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/providers/persistent/websocket.py", line 133, in _provider_specific_connect
    self._ws = await connect(self.endpoint_uri, **self.websocket_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    _transport, protocol = await self._create_connection()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1126, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1159, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 367, in runcode
    loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/main.py", line 525, in __async_init__
    await self.provider.connect()
  File "/Users/vadim/PyProjects/fastWeb3/.venv/lib/python3.12/site-packages/web3/providers/persistent/persistent.py", line 114, in connect
    raise ProviderConnectionError(
web3.exceptions.ProviderConnectionError: Could not connect to: wss://sepolia.infura.io/ws/v3/<MY-API-KEY>. Retries exceeded max of 5.
```

**Comment by fselmo** [comment] 2024-12-03 16:26
@4vadim4 I cannot reproduce this using my API key. I'm able to connect to both SSL endpoints for HTTPS and WebSocket (wss). Please make sure you are using the correct endpoint. I'm going to close this but if you find there is an issue with the library, please post a reproducible code snippet and we will be glad to re-open the issue. Best of luck.

**Closed by fselmo** 2024-12-03 16:26 UTC

**Comment by fselmo** [comment] 2024-12-03 16:31
Adding to this, make sure you are inside an async code block when you are using asyncio / async in Python.

```py

async def sepolia():
    w3 = AsyncWeb3(AsyncHTTPProvider(WEB3_HTTP_URI))
    print(await w3.eth.block_number)
    
asyncio.run(sepolia())
```

**Comment by 4vadim4** [comment] 2024-12-04 09:04
the problem was solved, 
thanks for your participation!!!
the problem was with certificates, i.e. here:
`python -m pip show  certifi`
it decided as follows:
 - updated brew;
`brew update && brew upgrade`
 - installed last python in new virtual env;
`pyenv install 3.13.0`
 - activated virtual environment for project;
 - code successfully executed.
