### ISSUE TITLE
Broken w3.geth.txpool.content()

### ISSUE THREAD

**Issue by purplebitch** [ethereum/web3.py#1556] opened 2019-12-22 19:41 UTC
### Expected behavior
`w3.geth.txpool.content()` returns a list of all full pending transactions

#### Actual behavior
When using `IPCProvider`, `w3.geth.txpool.content()` returns:
```
[redacted file name]
    txs = w3.geth.txpool.content()
  File "/usr/local/lib/python3.6/dist-packages/web3/module.py", line 12, in caller
    w3.manager.request_blocking(method_str, params),
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 94, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 81, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/ipc.py", line 238, in make_request
    timeout.sleep(0)
  File "/usr/local/lib/python3.6/dist-packages/web3/_utils/threads.py", line 68, in sleep
    self.check()
  File "/usr/local/lib/python3.6/dist-packages/web3/_utils/threads.py", line 61, in check
    raise self
web3._utils.threads.Timeout: 10 seconds
```

When using `WebsocketProvider`, `w3.geth.txpool.content()` returns:
```
    txs =  = w3.geth.txpool.content()
  File "/usr/local/lib/python3.6/dist-packages/web3/module.py", line 12, in caller
    w3.manager.request_blocking(method_str, params),
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 94, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 81, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/websocket.py", line 119, in make_request
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/websocket.py", line 107, in coro_make_request
    timeout=self.websocket_timeout
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

#### Steps to reproduce the behavior

Just running in the terminal `python3 fileName` where `fileName` has the following code included:
```
from web3 import Web3, IPCProvider, WebsocketProvider, HTTPProvider
IPCPath = '/root/.ethereum/geth.ipc'
w3 = Web3(IPCProvider(IPCPath))
txs = w3.geth.txpool.content().pending
```

#### Versions
web3.py 5.4.0
ubuntu 18.04.3 LTS
python3.6.9
Geth 1.9.9-stable

#### Extra info
I've tried the following which all had no effect:
 - using python3.7
 - different versions of web3.py (5.2.0, 5.3.0 etc)
 - changing the timeout in `w3 = Web3(IPCProvider(IPCPath, timeout=30))` between 1s and 30s

`w3.geth.txpool.status()` works fine
`w3.geth.txpool.inspect()` works fine
Doing:
```
geth attach
txpool.content
```
works fine

**Comment by kclowes** [comment] 2020-01-06 21:52
I can't replicate this issue when attaching to a geth node locally. Are you still seeing this error?

**Comment by fabdarice** [comment] 2020-09-27 22:12
Running into the same bug.
Running a geth node with --ws.api "eth,net,web3,txpool" and --http.api "eth,net,web3,txpool".

This command works fine: w3.geth.txpool.inspect()
But this one timeout, any idea?

```
w3.geth.txpool.content()
*** concurrent.futures._base.TimeoutError
```

**Comment by kclowes** [comment] 2020-09-28 16:31
@fabdarice I'm still not able to replicate. What version of web3 are you using?

**Comment by pipermerriam** [comment] 2020-09-28 17:51
It might be timing out for the txpool having a very large number of transactions and this it taking geth a long time to serialize and return them

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by fabdarice** [comment] 2020-09-28 19:15
@pipermerriam @kclowes
Connecting via HTTP works fine while fetching the content, it only fails if we're connecting via websocket.
```
Web3(Web3.WebsocketProvider(WEBSOCKET_URI))
```

Something to note is that `w3.geth.txpool.inspect()` works fine, only `content()` times out

**Comment by pipermerriam** [comment] 2020-09-28 21:34
@fabdarice what are you connecting to?  Geth node?  something else?

I think the next step here is to do some "futzing" to try and understand what is happening with your node.  Here are some things I would try:

1. bypass web3.py and make the request manually with something like the equivalent of curl and see if it succeeds.
2. restart your node, maybe on a private network or on a testnet where transaction volume should be lower and see if it still times out.
3. re-verify that HTTP/IPC/Websocket work/fail consistently and that your experience with the HTTPProvider working as expected wasn't a fluke, ideally by running your node with all three interfaces exposed and testing them all at roughly the same time.

**Comment by fabdarice** [comment] 2020-10-07 06:53
Apologies for the late answer.
I'm connecting to a local geth node. 

1) curl succeeds
2) Haven't tested that, but amount of pending is lower these days, still seeing the issue
3) HTTPProvider success all the time, whereas WebSocket always fail
4) will try that and keep you guys posted

**Comment by jquesnelle** [comment] 2020-11-21 01:22
I'm seeing the same thing @fabdarice is -- `content()` only works with `HTTPProvider`

**Comment by jimtje** [comment] 2021-01-04 05:49
I've had various issues with how WebsocketProvider seems to work and ultimately I figured the best way to figure things out is with doing some testing and logging things. I personally never ran into the IPCProvider problem unless there was some sort of permission issue with the actual file itself, which can be solved if you run the node not as root but as a regular user (assuming you're running it as a service at startup, of course). WebsocketProvider though, needed a bit of tweaking to get working properly. A very basic setup that works is:

```python
from web3 import Web3, IPCProvider, WebsocketProvider
import time

def events(ct):
    for k, v in ct["pending"].items():
        print(k, v)

def main():
    # w3 = Web3(IPCProvider("eth.ipc"))
    w3 = Web3(WebsocketProvider("ws://127.0.0.1:8546", websocket_timeout=360, websocket_kwargs={"max_size": 650000000}))
    # will not work without websocket timeout or max size set
    while True:
        try:
            events(w3.geth.txpool.content())
            time.sleep(1)
        except AttributeError:
            time.sleep(1)

if __name__ == "__main__":
    main()
```

If all you need is to get it working, well, that works for me at least (Debian 10, Python 3.8.6, Web3.py 5.12.3). 

To figure out what's going on under the hood though, I did some quick logging, the logs are here: [gist.github.com/jimtje/c0cdb6fd1310f6d5d7abc4f94c5e99c7](https://gist.github.com/jimtje/c0cdb6fd1310f6d5d7abc4f94c5e99c7)

```python
from web3 import Web3, IPCProvider, WebsocketProvider
import time
import logging

logging.basicConfig(filename="ipc_ws_debug.log", level=logging.DEBUG,
                        format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
                        datefmt="%H:%M:%S")
logger = logging.getLogger(__name__)

def ipc_logs():

    w3 = Web3(IPCProvider("eth.ipc"))
    try:
        for k, v in w3.geth.txpool.content()["pending"].items():
            logger.debug(v)
        time.sleep(1)
    except AttributeError:
        time.sleep(1)

def ws_logs():
    w3 = Web3(WebsocketProvider("ws://127.0.0.1:8546", websocket_timeout=360, websocket_kwargs={"max_size": 650000000}))
    # will not work without websocket timeout or max size set
    # while True:
    try:
        for k, v in w3.geth.txpool.content()["pending"].items():
            logger.debug(v)
        time.sleep(1)
    except AttributeError:
        time.sleep(1)

def main():
    ipc_logs()
    ws_logs()

if __name__ == "__main__":
    main()
```

It gets truncated but essentially it takes about the same time (around 3 seconds) for both methods to work through the pending txes in the mempool, but whereas IPCProvider begins iterating results immediately while with WS, the entire pending pool is read out and then iterated. This creates a bottleneck with the default settings since the default max\_size is _2 \*\* 20_ (1,048,576) and default timeout is 10, and if there are a ton of pending it's entirely possible that either one of the defaults won't allow the whole pool to get read, especially if you're not running a local node (I'm actually running a remote python interpreter through an ssh tunnel so it certainly feels like a much greater latency to me, although not to the actual script). I don't know if there's something specific to fix in the sense that this implementation seems to work as intended as long as the end user knows that the default settings may need some tweaking.

However I think this may be a pretty inefficient way to run a websocket client when it comes to processing txes in the mempool. I'd prefer using a trio/anyio type of setup since there exists a clear sort of parent/child task structure and each new block serves as a distinct demarcation point as to when the pool needs to be polled afresh, but that's somewhat off topic. For this issue I think as long as you add a healthy overhead to both websocket\_timeout and max\_size you should be okay.

**Comment by JorgeGAGR** [comment] 2021-07-05 21:12
> I've had various issues with how WebsocketProvider seems to work and ultimately I figured the best way to figure things out is with doing some testing and logging things. I personally never ran into the IPCProvider problem unless there was some sort of permission issue with the actual file itself, which can be solved if you run the node not as root but as a regular user (assuming you're running it as a service at startup, of course). WebsocketProvider though, needed a bit of tweaking to get working properly. A very basic setup that works is:
> 
> ```python
> from web3 import Web3, IPCProvider, WebsocketProvider
> import time
> 
> def events(ct):
>     for k, v in ct["pending"].items():
>         print(k, v)
> 
> def main():
>     # w3 = Web3(IPCProvider("eth.ipc"))
>     w3 = Web3(WebsocketProvider("ws://127.0.0.1:8546", websocket_timeout=360, websocket_kwargs={"max_size": 650000000}))
>     # will not work without websocket timeout or max size set
>     while True:
>         try:
>             events(w3.geth.txpool.content())
>             time.sleep(1)
>         except AttributeError:
>             time.sleep(1)
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> If all you need is to get it working, well, that works for me at least (Debian 10, Python 3.8.6, Web3.py 5.12.3). 
> 
> To figure out what's going on under the hood though, I did some quick logging, the logs are here: [gist.github.com/jimtje/c0cdb6fd1310f6d5d7abc4f94c5e99c7](https://gist.github.com/jimtje/c0cdb6fd1310f6d5d7abc4f94c5e99c7)
> 
> ```python
> from web3 import Web3, IPCProvider, WebsocketProvider
> import time
> import logging
> 
> logging.basicConfig(filename="ipc_ws_debug.log", level=logging.DEBUG,
>                         format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
>                         datefmt="%H:%M:%S")
> logger = logging.getLogger(__name__)
> 
> def ipc_logs():
> 
>     w3 = Web3(IPCProvider("eth.ipc"))
>     try:
>         for k, v in w3.geth.txpool.content()["pending"].items():
>             logger.debug(v)
>         time.sleep(1)
>     except AttributeError:
>         time.sleep(1)
> 
> def ws_logs():
>     w3 = Web3(WebsocketProvider("ws://127.0.0.1:8546", websocket_timeout=360, websocket_kwargs={"max_size": 650000000}))
>     # will not work without websocket timeout or max size set
>     # while True:
>     try:
>         for k, v in w3.geth.txpool.content()["pending"].items():
>             logger.debug(v)
>         time.sleep(1)
>     except AttributeError:
>         time.sleep(1)
> 
> def main():
>     ipc_logs()
>     ws_logs()
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> It gets truncated but essentially it takes about the same time (around 3 seconds) for both methods to work through the pending txes in the mempool, but whereas IPCProvider begins iterating results immediately while with WS, the entire pending pool is read out and then iterated. This creates a bottleneck with the default settings since the default max_size is _2 ** 20_ (1,048,576) and default timeout is 10, and if there are a ton of pending it's entirely possible that either one of the defaults won't allow the whole pool to get read, especially if you're not running a local node (I'm actually running a remote python interpreter through an ssh tunnel so it certainly feels like a much greater latency to me, although not to the actual script). I don't know if there's something specific to fix in the sense that this implementation seems to work as intended as long as the end user knows that the default settings may need some tweaking.
> 
> However I think this may be a pretty inefficient way to run a websocket client when it comes to processing txes in the mempool. I'd prefer using a trio/anyio type of setup since there exists a clear sort of parent/child task structure and each new block serves as a distinct demarcation point as to when the pool needs to be polled afresh, but that's somewhat off topic. For this issue I think as long as you add a healthy overhead to both websocket_timeout and max_size you should be okay.


Any implementation I try whilst trying to fetch .content() raises an 1006 error for me. As above, if I try with inspect() or status() this doesn't happen. Any tips?

**Comment by nimcon** [comment] 2021-08-03 11:50
Same issue here. Using Web3.py to connect to Geth on a local node via IPC
```w3 = Web3(Web3.IPCProvider("/home/ethereum/.ethereum/geth.ipc"))```
Running ```w3.geth.txpool.content()``` fails with

```
Traceback (most recent call last):
  File "myfile.py", line 45, in <module>
    result = w3.geth.txpool.content()
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/manager.py", line 180, in request_blocking
    response = self._make_request(method, params)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/manager.py", line 141, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 80, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/providers/ipc.py", line 265, in make_request
    timeout.sleep(0)
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/_utils/threads.py", line 89, in sleep
    self.check()
  File "/home/ethereum/venv/lib/python3.8/site-packages/web3/_utils/threads.py", line 82, in check
    raise self
web3._utils.threads.Timeout: 10 seconds
```

Other transaction pool functions such as ```w3.geth.txpool.inspect()``` and ```w3.geth.txpool.status()``` execute without error. Also, attaching to the node directly works fine
```
geth attach
> txpool.content
```

**Comment by kclowes** [comment] 2021-08-04 20:16
Thanks for digging into this @jimtje. 

@nimcon or @JorgeGAGR - have you tried with the workaround that @jimtje found increasing the `websocket_timeout` and adding `max_size`? 
`w3 = Web3(WebsocketProvider("ws://127.0.0.1:8546", websocket_timeout=360, websocket_kwargs={"max_size": 650000000}))`

**Comment by jimtje** [comment] 2021-09-02 23:17
Yeah I can't exactly be sure what the exact issue is here @JorgeGAGR since error 1006 indicates a problem with the websocket connection itself and not necessarily with the command you're trying to call. Not sure what sort of setup you have running but the code still works for me, now on Python 3.9.5 and on the latest release of web3.py. If you're running the node, can you up the verbosity on logging for the node itself to see if it returns any errors specifically? I suspect it's related to the size of the content still, but the error message could cover a lot of different possible issues.

@nimcon Can you initialize with 
```w3 = Web3(IPCProvider("/home/ethereum/.ethereum/geth.ipc", timeout=360)```
instead? It seems that the changes made to the library since I posted have included a default timeout of 10 which is too short to grab the entire pending pool. If 360 is still too short, feel free to up it further.

**Comment by glenvollmer** [comment] 2021-12-18 01:02
anyone figure this issue out??? I am having the same problem but with the IPC connection instead of Websocket

**Comment by glenvollmer** [comment] 2021-12-27 23:38
???

**Comment by glenvollmer** [comment] 2021-12-27 23:39
> I'm seeing the same thing @fabdarice is -- `content()` only works with `HTTPProvider`

why though? Shouldn't is also work with the IPC connection as well?

**Comment by darksidergod** [comment] 2022-01-04 06:37
Hey everyone! I am running a local node on fast-sync mode and am getting empty objects returned from the web3.eth.txpool.inspect() call. I am using IPC Provider from the endpoint opened by my local node itself.

**Comment by jimtje** [comment] 2022-01-05 01:23
> Hey everyone! I am running a local node on fast-sync mode and am getting empty objects returned from the web3.eth.txpool.inspect() call. I am using IPC Provider from the endpoint opened by my local node itself.

Hey, I don't think the command works until your local node is actually fully sync-ed

**Comment by tsarbuig** [comment] 2022-07-21 22:48
Hi guys, we're more than 1 yeah after and still running the same issues here...

I tried to use the new AsyncHTTPProvider provided in last Web3 version, but with no luck...

So, I have 3 questions : 

1/ Anyone has an example of AsyncHTTPProvider implementation to replace this code ?
`tx_pool = client.geth.txpool.content()['pending'].items()`

2/ Does anyone has fixed the timeout error on IPC ? Even after having set it to 360, still having this kind of issue : 
`web3._utils.threads.Timeout: 360 seconds`

3/ I have some missed Tx, that seems not to be processed... even when I use Websockets with the suggested parameters above (websocket_timeout=360, websocket_kwargs={"max_size": 650000000})   my software still miss some Tx : do you have the same problem?

@jimtje  maybe ? You seem to be a pro :)


Thanks a lot guys

**Comment by fselmo** [comment] 2024-02-26 18:12
This was tested with the new `WebsocketProvider` coming in *web3.py* `v7` (available in `v6` as `WebsocketProviderV2`), as well as `AsyncIPCProvider` and `IPCProvider` against a fully synced node and cannot be reproduced. All seem to be working as expected. 

I'm going to close this but that shouldn't close the door on conversation if this still exists for anyone. I would try to make sure you are fully synced if you're still experiencing issues.

**Closed by fselmo** 2024-02-26 18:12 UTC
Labels: priority: p3 normal
