### ISSUE TITLE
connect to infuro  web3.personal.newAccount errro

### ISSUE THREAD

**Issue by purplecity** [ethereum/web3.py#1093] opened 2018-10-08 11:40 UTC
* Version: new
* Python:3.6.5
* OS: macox

connect to infura .  i want to create a eth account. but errro!!

code is:

from web3 import Web3
from web3.personal import Personal

web3=Web3(Web3.HTTPProvider("https://mainnet.infura.io/v3/API_KEY_XXXXXXXXXX",request_kwargs={"timeout":10}))
print(web3.personal.newAccount("purplecity"))

error message:

ERROR: requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://mainnet.infura.io/v3/API_KEY_XXXXXXXXXX

**Comment by pipermerriam** [comment] 2018-10-08 16:35
Infura does not support anything *stateful*.  You can't use the `w3.personal` module unless you're connected to a go-ethereum node.

**Comment by carver** [comment] 2018-10-09 00:52
Closing because it's not a bug, but feel free to continue to comment for support.

**Closed by carver** 2018-10-09 00:52 UTC

**Comment by carver** [comment] 2018-10-09 02:29
If you want to use Infura and sign transactions in web3.py, you'll need to use local keys. See why and how, here: https://web3py.readthedocs.io/en/stable/web3.eth.account.html

**Comment by purplecity** [comment] 2018-10-09 02:36
> If you want to use Infura and sign transactions in web3.py, you'll need to use local keys. See why and how, here: https://web3py.readthedocs.io/en/stable/web3.eth.account.html

thanks.  sorry I am new about eth project.  I want know is there have any way to create eth acount when use web3.py to connect infura

**Comment by carver** [comment] 2018-10-09 02:40
No

**Comment by purplecity** [comment] 2018-10-09 03:44
> No

so I need  local nodes like use geth,parity to sync nodes。then invoke api to create eth account？ I don't use Mint just use codes to create eth account.

**Comment by carver** [comment] 2018-10-09 17:05
Sure, running a local node is a good way to have your node manage your keys. Then you would not use the `w3.eth.account` API, which is for locally-managed keys.

**Comment by pipermerriam** [comment] 2019-01-04 23:54
@slishady take a look at https://web3py.readthedocs.io/en/latest/middleware.html#signing

It should provide a reasonably simple way to do what you're trying to do without you having to manually sign the transaction yourself.

In your code abou

> when i check the balance of signed_txn, it does not change after this procedure means it does not work. so are there any methds to do it?

The reason for this is that you still have to broadcast the transaction.  If you take a look at the `signed_txn` there will be a `rawTransaction` value.  This can be sent using `w3.eth.sendRawTransaction(signed_txn['rawTransaction'])` which returns the hash of the transaction.  Simply signing it doesn't broadcast it to the network.
