### ISSUE TITLE
tx.hash is now hexByte encoded not string

### ISSUE THREAD

**Issue by boosth** [ethereum/web3.py#834] opened 2018-05-09 17:13 UTC
* Version: 4.2.0
* Python:3.5
* OS: linux

Previously with 3.6  I could include the tx.hash from tx = web3.getTransaction()  in the output for django jsonResponse.

Now I receive an error : 

HexBytes('0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592') is not JSON serializable

If I wrap str(tx.hash) before passing to jsonResponse()   I see the following:

"txhash": "b'q\\x99N\\xddteb\\xb0m\\x00G\\xc0\\xfe\\xf0\\x15t3o9\\xe8\\x89s\\xf9\\x8f\\x06lD\\x9e\\x10\\x145\\x92'"

I have also tried web3.toText(tx.hash) but that also fails with the following error:

'utf-8' codec can't decode byte 0x99 in position 1: invalid start byte

What is the correct method for using the tx.hash as a normal string in the same way as 3.6.x?

**Comment by voith** [comment] 2018-05-09 17:20
have a look at https://github.com/ethereum/web3.py/issues/782#issuecomment-383464754.

**Comment by webjunkie01** [comment] 2018-05-09 17:20
Use the method web3.toHex to return its hexadecimal representation.

**Comment by carver** [comment] 2018-05-09 20:39
Additionally, there is a `hex()` method on the `HexBytes` class. Like so:

```py
>>> HexBytes('0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592').hex()
'0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592'
```

---

Closing because it's not a bug, but feel free to continue to comment for support.

**Closed by carver** 2018-05-09 20:39 UTC

**Comment by ccding** [comment] 2019-05-04 18:46
> ```python
> >>> HexBytes('0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592').hex()
> '0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592'
> ```

It raises exceptions. I have to use `bytes(HexBytes(...)).hex()`

**Comment by carver** [comment] 2019-05-06 20:51
> > ```python
> > >>> HexBytes('0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592').hex()
> > '0x71994edd746562b06d0047c0fef01574336f39e88973f98f066c449e10143592'
> > ```
> 
> It raises exceptions. I have to use `bytes(HexBytes(...)).hex()`

This should be its own bug report, that workaround should not be necessary. Please open at https://github.com/ethereum/hexbytes/issues

FWIW, that one-liner works on my install of hexbytes v0.1.0. So we'll need your pip environment, the full stack trace, etc, in order to provide an help.
